// TeaService — the daily sermon plus a 30-card archive from the Grace API.
// Falls back to a bundled copy of the same 30 so Tea works offline; the fallback
// is generated from backend/src/lib/teaCatalog.ts so the two cannot drift.
// Mirrors StoryService caching and persists like/save engagement to the server.
import { api } from '../api/client';
import { AuthService } from './AuthService';
import { StorageService, KEYS } from './StorageService';

const FALLBACK_TEAS = [
  {"id":"vashti-no","cardTitle":"She Would Not Come","heat":2,"badge":"Today's tea","hook":"Okay bestie I need you to sit all the way down for this one… …","tea":"This king owns 127 provinces and throws a seven-day party so massive the whole city is invited. Day seven he’s wasted and decides he wants his wife to walk out in the crown so every man can stare at her. Meanwhile she’s throwing her own feast for the women in the same palace. She says no.… No explanation. Just no. He doesn’t even go talk to her. He calls an emergency meeting of advisors like this is a national security threat. One of them stands up and basically says, “If the other women hear about this they’re all gonna start disrespecting their husbands.” So they pass a permanent law: every man must rule his own house. Letters go out in every language of the empire. One woman said no at a dinner party… and an entire empire had a complete meltdown. I’m obsessed with her.","ref":"Esther 1:12","book":"Esther","chapter":1,"mood":"dark","order":1,"durationSeconds":45},
  {"id":"ruth-field","cardTitle":"Loyalty In The Barley","heat":1,"badge":"Plot twist","hook":"No because why is this the most soft launch of a dynasty I’ve ever seen… …","tea":"Naomi loses her husband and both her sons. She’s left with two foreign daughters-in-law and tells them both to go home because she has nothing left to give. One leaves. The other one, Ruth, looks her dead in the eye and says “where you go I go, your people my people, your God my God.” That’s not cute. That’s a lifelong vow. They walk into Bethlehem broke during harvest. Ruth starts gleaning, literally picking up other people’s leftovers in the field. And somehow she “happens” to land in the field of a rich relative named Boaz. He notices her immediately, tells his men not to touch her, then quietly tells them to drop extra grain for her on purpose. She goes home with an insane amount of barley. Fast forward: he marries her, they have a son, and that son’s grandson is King David. Broke foreign widow picking up scraps… three generations later her bloodline is on the throne. I can’t.","ref":"Ruth 2:2","book":"Ruth","chapter":2,"mood":"light","order":2,"durationSeconds":53},
  {"id":"deborah-palm","cardTitle":"Court Under A Palm","heat":2,"badge":"Receipts","hook":"Wait wait wait… a woman was literally the judge of the whole nation and nobody talks about it enough… …","tea":"Deborah. The text doesn’t say she “helped” or “advised.” It says she judged Israel. She held court under a palm tree and people came to her for actual legal decisions. She summons the military commander Barak and gives him God’s battle plan. This grown man looks at her and says, “I’ll only go if you come with me.” She goes… but she tells him to his face: “This victory won’t be yours. The Lord is going to hand the enemy over to a woman.” And that’s exactly what happens. Sisera ends up dead in a tent with a hammer through his head. So the official record is: the prophetess gave the orders, the general needed a babysitter, and another woman finished the job. Palm tree. Entire nation. I’m screaming.","ref":"Judges 4:4","book":"Judges","chapter":4,"mood":"dark","order":3,"durationSeconds":42},
  {"id":"abigail-intercept","cardTitle":"She Intercepted A King","heat":2,"badge":"Hot take","hook":"Girl the way she pulled up on 400 armed men like it was nothing… …","tea":"David is about to commit a massacre. Some rich guy named Nabal just insulted him after David’s men protected his sheep for free, so David straps on his sword and takes 400 men. He’s going to kill every male in the house. A servant runs to Nabal’s wife Abigail like “your husband just signed our death warrant.” She doesn’t cry. She does inventory. Loads up donkeys with food and wine and sends them ahead. Doesn’t even tell her husband. Then she rides out herself, meets 400 armed men on the road, and starts talking. Calls her own husband a fool to David’s face. Talks the future king completely down. The 400 men turn around. She goes home, waits until her husband is sober the next morning, tells him what she did… and he has a stroke basically. Ten days later he’s dead. David hears about it and sends for her. She becomes his wife. Girl said “not today” to 400 swords and a future king… and won.","ref":"1 Samuel 25:18","book":"1 Samuel","chapter":25,"mood":"light","order":4,"durationSeconds":55},
  {"id":"mary-yes","cardTitle":"The Most Costly Yes","heat":1,"badge":"Today's tea","hook":"Bestie she said yes to a plan that could’ve gotten her killed and I’m still not over it… …","tea":"Gabriel shows up in a random village nobody cares about and tells a girl who’s engaged (not married) that she’s about to get pregnant by the Holy Spirit and her son will be the forever king. She’s troubled by the greeting first, not even the angel. Then when the actual news lands her only question is “how, since I’ve never been with a man?” She’s not asking for proof. She’s asking logistics. In her village this could ruin her life or get her killed. And she still says yes. “Be it unto me according to thy word.” Yes to a plan she couldn’t verify, in a town that could count. I’m not okay.","ref":"Luke 1:38","book":"Luke","chapter":1,"mood":"dark","order":5,"durationSeconds":37},
  {"id":"martha-mary","cardTitle":"The Better Part","heat":1,"badge":"Plot twist","hook":"No because Jesus really said her name twice like he was talking to his favorite person… …","tea":"Jesus walks into a house. Martha is the host and she’s drowning in the work, cooking, serving, stressed. Her sister Mary is just sitting at Jesus’ feet listening. Martha finally snaps and goes over Mary’s head: “Lord, don’t you care that my sister left me to do everything alone? Tell her to help me.” She’s not asking. She’s ordering him. And instead of scolding her he says her name twice, “Martha, Martha”, the way you talk to someone you love who’s spiraling. Then he tells her she’s worried about too many things, and Mary chose the one thing that can’t be taken from her. He never tells Mary to get up. He never says the serving was wrong. He basically tells Martha she’s allowed to sit down too. I’m soft for that.","ref":"Luke 10:42","book":"Luke","chapter":10,"mood":"light","order":6,"durationSeconds":44},
  {"id":"well-woman","cardTitle":"She Left The Waterpot","heat":3,"badge":"Wild","hook":"Okay the first person Jesus fully revealed himself to was a woman with five exes and I’m screaming… …","tea":"Jesus is tired and sits by a well at the hottest part of the day. A Samaritan woman comes to draw water. He asks her for a drink (already scandalous) and the conversation goes sideways fast. He offers her living water. She wants it. He says go call your husband. She says she doesn’t have one. He goes, “You’re right… you’ve had five. And the one you have now isn’t your husband.” He’s not shaming her. He’s telling her he already knew every messy detail and he’s still sitting there talking to her. Then she brings up the Messiah and he looks at her and says “I that speak unto thee am he.” First time in the whole Gospel he says it that clearly… to her. She leaves her waterpot. Just abandons it. Runs back to town and becomes the first evangelist. Five exes and a waterpot. I’m obsessed.","ref":"John 4:28","book":"John","chapter":4,"mood":"dark","order":7,"durationSeconds":47},
  {"id":"esther-uninvited","cardTitle":"If I Perish","heat":2,"badge":"Hot take","hook":"She walked in knowing it could kill her and still said “if I perish, I perish”… …","tea":"There’s a law in Persia: if you walk into the king’s presence without being summoned, you die. Unless he holds out the golden scepter. Esther tells Mordecai she hasn’t been called in thirty days. She’s the queen and she has no idea if she’s still safe. Mordecai hits her with the hardest truth: don’t think the palace will protect you. If you stay silent, deliverance will come from somewhere else… but you and your family might not make it. Then he drops the line: “Who knows if you came to the kingdom for such a time as this?” She fasts three days and sends back four words: “If I perish, I perish.” Third day she walks in. The king holds out the scepter. She lives… and then throws the dinner party that takes down the second most powerful man in the empire. I’m obsessed with her courage.","ref":"Esther 4:16","book":"Esther","chapter":4,"mood":"light","order":8,"durationSeconds":53},
  {"id":"hannah-prayer","cardTitle":"Only Her Lips Moved","heat":1,"badge":"Today's tea","hook":"The priest really called her drunk for praying too hard and I’m not over it… …","tea":"Hannah can’t have kids. Her husband’s other wife has plenty and provokes her about it every single year at the place of worship. Hannah stops eating and just weeps. Her husband tries to comfort her with the most well-meaning terrible line ever: “Am I not better to you than ten sons?” She gets up, goes to the temple, and prays so hard that only her lips are moving. No sound. The priest watches her and decides she’s drunk. Out loud. “How long will you be drunk? Put away your wine.” She doesn’t shrink. She just says, “No my lord, I’m a woman of a sorrowful spirit. I haven’t had anything to drink. I’ve been pouring out my soul before the Lord.” Most honest prayer in the building and the priest called her a drunk. She walks out still childless… but the text says her face wasn’t sad anymore. I’m soft for her.","ref":"1 Samuel 1:13","book":"1 Samuel","chapter":1,"mood":"dark","order":9,"durationSeconds":47},
  {"id":"magdalene-first","cardTitle":"The First To See","heat":2,"badge":"Receipts","hook":"Bestie, you are not ready… they all went home from the tomb, and she stayed… …","tea":"Peter. John. They ran to the tomb, looked inside, saw the empty linen, and \"went away again unto their own home.\" Gone. Mary Magdalene stays outside crying. She sees two angels sitting where the body had been. She turns around and Jesus is standing right there, and she does not know it is Him. \"She, supposing him to be the gardener, saith unto him, Sir, if thou have borne him hence, tell me where thou hast laid him, and I will take him away.\" She is standing in a graveyard negotiating to carry a grown man's body by herself. Then He says one word. \"Jesus saith unto her, Mary.\" That is all it took. First human being on the planet to see the risen Christ. And the first one He sends: \"go to my brethren.\" The first preacher of the resurrection is a woman Luke says He had cast seven devils out of. He could have appeared to anybody. He picked her.","ref":"John 20:16","book":"John","chapter":20,"mood":"light","order":10,"durationSeconds":56},
  {"id":"rahab-rope","cardTitle":"The Scarlet Cord","heat":3,"badge":"Wild","hook":"She lied to the king, hid the spies, and negotiated her whole family out of a war… …","tea":"Two Israelite spies sneak into Jericho and end up at Rahab’s house. The text does not soften what she does for a living. The king finds out and sends soldiers. Rahab hides the spies, looks the soldiers dead in the face, and lies. Sends them the wrong way. Then she goes up to the roof and tells the spies the real reason: “I know your God has given you this land. We heard what happened at the Red Sea and our hearts melted. Your God is God in heaven and on earth.” That’s a full confession of faith from a Canaanite sex worker, sharper than most of Israel at the time. Then she negotiates… not for herself. For her whole family. Father, mother, brothers, sisters. Scarlet cord in the window. Her household lives. And Matthew puts her in the family line of Jesus. I’m obsessed.","ref":"Joshua 2:4","book":"Joshua","chapter":2,"mood":"dark","order":11,"durationSeconds":45},
  {"id":"jael-tent","cardTitle":"Milk, Then A Hammer","heat":3,"badge":"Wild","hook":"She gave him milk, tucked him in, then finished the war… …","tea":"Sisera has been crushing Israel for twenty years with 900 iron chariots. His army finally collapses and he’s running for his life on foot. He ducks into the nearest tent. A woman named Jael comes out all soft: “Turn in, my lord. Fear not.” He asks for water. She gives him milk. Covers him up. He falls asleep. Then she takes a tent peg and a hammer… and goes softly. Walks out, finds the commander hunting him, and says “Come, I’ll show you the man you’re looking for.” The victory song calls her blessed above women. And it ends with Sisera’s mother waiting at the window wondering why his chariot is taking so long while her friends reassure her he’s just dividing the girls. She served milk and a murder. I’m scared of her and I love her.","ref":"Judges 4:21","book":"Judges","chapter":4,"mood":"dark","order":12,"durationSeconds":42},
  {"id":"tamar-veil","cardTitle":"She Took His Signet","heat":3,"badge":"Wild","hook":"She took his government ID and then almost got burned alive for it… …","tea":"Tamar marries Judah’s oldest son. He dies. Next brother. He dies too. Judah has one more son but parks her at her dad’s house “until he’s grown” and then never sends for her. Years pass. She’s stuck with no rights. So she puts on a veil, sits by the road, and when Judah walks past he doesn’t recognize her and propositions her. She says fine, but I need a pledge. He asks what. She says your signet, your bracelets, and your staff. That’s his government ID. Three months later people tell Judah she’s pregnant and he’s ready to have her burned alive. She sends back his own signet and staff with a note that basically says “recognize these?” In front of everyone he has to admit: “She hath been more righteous than I.” She played him so clean he had to say it out loud. I’m on the floor.","ref":"Genesis 38:26","book":"Genesis","chapter":38,"mood":"light","order":13,"durationSeconds":54},
  {"id":"miriam-song","cardTitle":"Timbrel On The Shore","heat":1,"badge":"Plot twist","hook":"The sea just closed on an entire army and she reached for a tambourine… …","tea":"Israel just walked through the sea on dry ground and watched the water crash down on the entire Egyptian army. Moses and the people sing first. Then Miriam the prophetess grabs a tambourine. All the women follow her with instruments and dancing. She leads the response: “Sing to the Lord, for he has triumphed gloriously. The horse and his rider he has thrown into the sea.” The text calls her two things in one verse: prophetess, and sister of Aaron. When the water closed and the impossible happened… she was the one who reached for an instrument. I’m soft for that energy.","ref":"Exodus 15:20","book":"Exodus","chapter":15,"mood":"light","order":14,"durationSeconds":37},
  {"id":"shunammite","cardTitle":"I Will Not Leave","heat":2,"badge":"Receipts","hook":"Her son died on her lap and she still said “it shall be well”… …","tea":"This wealthy woman notices the prophet Elisha keeps passing through and builds him a whole room, bed, table, chair, lamp. He wants to repay her. She says she’s fine. He gives her a son anyway. Years later the boy is out in the field, says “my head, my head,” and dies on her lap at noon. She carries him upstairs, lays him on the prophet’s bed, shuts the door, and calls for a donkey. Her husband asks why she’s going. She just says “it shall be well.” Doesn’t tell him the child is dead. Doesn’t ask permission. She rides to Elisha, blows past his servant, grabs the prophet by the feet and says “as the Lord lives and as your soul lives, I will not leave you.” He gets up and follows her. Her son died on her lap and she still said “it shall be well” and refused to let go. I’m in awe.","ref":"2 Kings 4:30","book":"2 Kings","chapter":4,"mood":"dark","order":15,"durationSeconds":44},
  {"id":"widow-oil","cardTitle":"Borrow Not A Few","heat":1,"badge":"Today's tea","hook":"The miracle stopped exactly when the jars ran out and that detail is everything… …","tea":"A widow’s husband dies. The creditor is coming, not for the furniture, for her two sons. They’re about to be taken as slaves to pay the debt. Elisha asks her what she has in the house. She says nothing… except a little jar of oil. He tells her to go borrow empty vessels from all her neighbors. And then he says the line: “borrow not a few.” She shuts the door with her sons and starts pouring. The oil keeps coming. Vessel after vessel. Until she asks for one more and her son says there are no more left. The oil stops exactly when the containers run out. She sells it, pays the debt, keeps her sons, and lives on the rest. The miracle matched the size of her vessels. I’m soft.","ref":"2 Kings 4:6","book":"2 Kings","chapter":4,"mood":"light","order":16,"durationSeconds":45},
  {"id":"bleeding-woman","cardTitle":"Twelve Years, One Touch","heat":2,"badge":"Hot take","hook":"Bestie, twelve years… every doctor, every coin, and it only got worse… …","tea":"Mark five. Twelve years of an issue of blood, and Mark says she \"had suffered many things of many physicians, and had spent all that she had, and was nothing bettered, but rather grew worse.\" Broke. Exhausted. Out of options. She hears Jesus is moving through a crowd and she does not ask for a meeting. She gets in behind Him in the crush of bodies and touches His clothes, because she had said, \"If I may touch but his clothes, I shall be whole.\" \"And straightway the fountain of her blood was dried up.\" Twelve years, ended, on contact. Then Jesus stops a moving crowd to ask who touched Him. She is frightened and shaking. She comes and falls down in front of everybody and tells Him all the truth. And He does not scold her for it. \"Daughter, thy faith hath made thee whole; go in peace, and be whole of thy plague.\" Daughter. Out loud. In front of all of them. No more hiding.","ref":"Mark 5:34","book":"Mark","chapter":5,"mood":"dark","order":17,"durationSeconds":50},
  {"id":"canaanite-mother","cardTitle":"She Argued For Crumbs","heat":3,"badge":"Wild","hook":"Okay lock in, this one is unhinged… she argued with Jesus in public and walked away with the win… …","tea":"Jesus is up in Gentile territory. A woman of Canaan comes after Him crying out about her demonized daughter. \"But he answered her not a word.\" Nothing. The disciples get irritated and ask Him to send her away because she keeps crying after them. He tells her He was not sent but unto the lost sheep of the house of Israel. She hits her knees anyway. \"Lord, help me.\" And then He says the hardest line in the passage. \"It is not meet to take the children's bread, and to cast it to dogs.\" She does not flinch. She takes His own metaphor and turns it around on Him. \"Truth, Lord: yet the dogs eat of the crumbs which fall from their masters' table.\" And He stops cold. \"O woman, great is thy faith: be it unto thee even as thou wilt.\" Her daughter was made whole from that very hour. She argued in public, on crumbs, and Scripture keeps the receipt.","ref":"Matthew 15:27","book":"Matthew","chapter":15,"mood":"light","order":18,"durationSeconds":57},
  {"id":"anna-temple","cardTitle":"Decades Of Showing Up","heat":1,"badge":"Plot twist","hook":"Eighty-four years of showing up with zero proof… and she still got the scoop… …","tea":"Anna. Prophetess. From the tribe of Asher, one of the northern tribes that got scattered centuries earlier. Most people had written her people off. Married seven years. Then her husband dies. Luke says she was a widow of about eighty-four years. Decades. She never left the temple. Fasting and praying night and day. Waiting for something she had no proof was coming. One ordinary morning a poor couple walks in with a newborn to do the legal requirement. Nothing about it looks special. She walks in at that exact instant, sees the baby, and then goes out and tells everyone in Jerusalem who’s been waiting for redemption. Eighty-four years of nothing… and she got the scoop. I’m soft for the long game.","ref":"Luke 2:38","book":"Luke","chapter":2,"mood":"dark","order":19,"durationSeconds":45},
  {"id":"lydia-house","cardTitle":"And She Constrained Us","heat":2,"badge":"Receipts","hook":"She literally strong-armed the apostles into moving into her house… …","tea":"Paul and the team get to Philippi. On the Sabbath they go to the river where the women gather to pray. There’s Lydia. Seller of purple, luxury fabric. She has money and runs a business. The Lord opens her heart. She gets baptized along with her whole household. Then she makes an offer that isn’t really an offer: “If you judge me faithful to the Lord, come stay at my house.” Luke adds four words that tell you everything: “And she constrained us.” She would not take no. Later in the same chapter, after the earthquake and the jailer’s household getting baptized, where do they go? Back to Lydia’s house. Her house became the base of operations. Not asked. Told. I’m obsessed with her energy.","ref":"Acts 16:15","book":"Acts","chapter":16,"mood":"light","order":20,"durationSeconds":45},
  {"id":"priscilla-teach","cardTitle":"She Taught The Teacher","heat":2,"badge":"Hot take","hook":"The most eloquent preacher in the city was about eighty percent right. She took him aside and fixed it.","tea":"Acts eighteen. A man named Apollos shows up in Ephesus. Born in Alexandria. The text calls him eloquent, and mighty in the scriptures. He teaches diligently the things of the Lord. He is genuinely gifted. And then one clause changes everything. \"Knowing only the baptism of John.\" He is brilliant, and he is behind. He has most of it, and he is preaching with total confidence. So he starts speaking boldly in the synagogue. And Aquila and Priscilla hear him. And here is the move. They do not stand up in the middle of the synagogue and correct him publicly. They do not go home and subtweet him. \"Whom when Aquila and Priscilla had heard, they took him unto them, and expounded unto him the way of God more perfectly.\" Took him aside. Filled in what was missing. Protected the ministry while they fixed it. And Apollos goes on to help the believers enormously and to convince people publicly. One more thing, and I want to be straight with you. In several places her name is listed first. Including this one. Luke never tells us why, so treat the theories as theories. What you can see on the page is that she taught the teacher.","ref":"Acts 18:26","book":"Acts","chapter":18,"mood":"dark","order":21,"durationSeconds":63},
  {"id":"sarah-laugh","cardTitle":"Laughter Behind The Tent","heat":2,"badge":"Plot twist","hook":"Girl, the shade is biblical… she laughed at God from behind the tent and He clocked it… …","tea":"Genesis eighteen. Three men show up at Abraham's tent, and one of them announces that Sarah is going to have a son. Sarah is ninety years old. She is listening from the tent door behind them. And she laughs. Not out loud. \"Therefore Sarah laughed within herself, saying, After I am waxed old shall I have pleasure, my lord being old also?\" Within herself. Nobody in that tent heard a thing. And the very next verse is the Lord turning to Abraham and asking, \"Wherefore did Sarah laugh, saying, Shall I of a surety bear a child, which am old?\" He heard it. So Sarah panics and lies straight to God. \"I laughed not.\" The text tells you why: she was afraid. And He does not let her have it. \"Nay; but thou didst laugh.\" Then comes the ending nobody plans for. She has the baby. They name him Isaac, which means he laughs. And she says, \"God hath made me to laugh, so that all that hear will laugh with me.\" She laughed because she doubted. He made her laugh for real.","ref":"Genesis 18:15","book":"Genesis","chapter":18,"mood":"light","order":22,"durationSeconds":66},
  {"id":"hagar-seen","cardTitle":"Thou God Seest Me","heat":2,"badge":"Today's tea","hook":"A pregnant runaway slave is the first person in the Bible to give God a name.","tea":"Sarai cannot have children. So she gives her Egyptian handmaid Hagar to Abram, to get a child through her. Nobody asks Hagar anything. She is a solution to someone else's problem. She conceives. Tension explodes. Sarai says to Abram, \"My wrong be upon thee.\" And Abram, husband of the year, says, \"Behold, thy maid is in thy hand; do to her as it pleaseth thee.\" He hands her back. And the text says Sarai dealt hardly with her. So Hagar runs. Pregnant. Alone. No plan, because there is not one. And the angel of the Lord finds her by a spring of water. Not a temple. Not a camp. A spring, in the middle of nowhere. And he says, \"Hagar, Sarai's maid, whence camest thou? and whither wilt thou go?\" Where did you come from. Where are you going. She answers the first one. \"I flee from the face of my mistress Sarai.\" She does not answer the second. She has nowhere to go and they both know it. Then he tells her to call the boy Ishmael, because the Lord hath heard thy affliction. And then Hagar does something nobody in Scripture has done yet. She names God. \"Thou God seest me.\" A runaway. A foreigner. A slave. And she is the one who gets to say it first.","ref":"Genesis 16:13","book":"Genesis","chapter":16,"mood":"dark","order":23,"durationSeconds":65},
  {"id":"zelophehad","cardTitle":"Five Sisters Speak Right","heat":3,"badge":"Wild","hook":"Five sisters argued property law in front of the entire nation. God said they were right.","tea":"Numbers twenty-seven. Their names are Mahlah, Noah, Hoglah, Milcah and Tirzah. Scripture lists every single one. Their father died in the wilderness with no sons. Under the rules as they stood, land moved through sons. So his name and his portion simply vanish. And these five women do not petition quietly. They stood before Moses. And before Eleazar the priest. And before the princes and all the congregation. At the door of the tabernacle. That is the entire leadership of the nation, plus everybody else, and five sisters walk up and make a legal argument. \"Why should the name of our father be done away from among his family, because he hath no son? Give unto us therefore a possession among the brethren of our father.\" And Moses does not rule on it. He does not wing it. He does not send them home. \"And Moses brought their cause before the Lord.\" And the answer comes back. \"The daughters of Zelophehad speak right.\" Speak right. God agreed with them. On the record. And the inheritance law of Israel was rewritten because five women showed up and asked.","ref":"Numbers 27:7","book":"Numbers","chapter":27,"mood":"light","order":24,"durationSeconds":67},
  {"id":"huldah-scroll","cardTitle":"They Asked The Prophetess","heat":2,"badge":"Receipts","hook":"Bestie, they skipped every man on the list… and went straight to her… …","tea":"They find the lost book of the law in the temple. King Josiah hears it read out, tears his clothes, and needs to know what God actually says about the mess Judah is in. So he sends a delegation, and the high priest himself is on it. They do not take the question to a priest. They do not take it to Jeremiah, who is prophesying in Judah in those same years. The text names all five of them, Hilkiah the priest, Ahikam, Achbor, Shaphan and Asahiah, and says they \"went unto Huldah the prophetess.\" A married woman living in Jerusalem. And she does not hedge and she does not soften it. \"Thus saith the LORD God of Israel, Tell the man that sent you to me.\" Tell the man that sent you. Then she delivers it: judgment is coming on this place, but because the king's heart was tender, he will go to his grave in peace. The reform of an entire nation turns on her answer. Scripture never once explains itself for asking her.","ref":"2 Kings 22:14","book":"2 Kings","chapter":22,"mood":"dark","order":25,"durationSeconds":50},
  {"id":"widow-mite","cardTitle":"All Her Living","heat":1,"badge":"Plot twist","hook":"He sat down opposite the treasury and watched people give. On purpose.","tea":"Mark twelve. And the setup is the part everyone skips. \"Jesus sat over against the treasury, and beheld how the people cast money into the treasury.\" He sat down. And watched. Deliberately. And many that were rich cast in much. That is in the text too. It is not a lie. They gave a lot. Then a certain poor widow comes and throws in two mites. And Mark actually converts the currency for his readers, which tells you how small it was. Two mites, which make a farthing. And Jesus calls his disciples over. He wants them to see this specifically. \"Verily I say unto you, That this poor widow hath cast more in, than all they which have cast into the treasury.\" More than all of them. Combined. And then he does the maths out loud. \"For all they did cast in of their abundance; but she of her want did cast in all that she had, even all her living.\" All her living. Not a percentage. Everything. He is not measuring the gift. He is measuring what was left afterwards.","ref":"Mark 12:44","book":"Mark","chapter":12,"mood":"light","order":26,"durationSeconds":60},
  {"id":"joanna-fund","cardTitle":"Of Their Own Substance","heat":2,"badge":"Hot take","hook":"One of the women funding the ministry was married to Herod's household manager. She was inside the court that killed John.","tea":"Luke chapter eight. Three verses that get skipped constantly. Jesus is going through every city and village preaching, and the twelve are with him. Standard. And then Luke adds, \"and certain women, which had been healed of evil spirits and infirmities.\" And he names them. Mary called Magdalene, out of whom went seven devils. Joanna. Susanna. And many others. Stop on Joanna for a second, because Luke drops her job title like it is nothing. \"Joanna the wife of Chuza Herod's steward.\" Herod's steward. That is a household manager inside the royal court. The same court. That is not a small detail. That is a woman with access, money, and an enormous amount to lose by being on this road at all. And then the line. \"Which ministered unto him of their substance.\" Their substance. Their own resources. Luke did not have to write any of that down. Nobody was auditing him. He wanted somebody two thousand years later to know exactly who was paying for it.","ref":"Luke 8:3","book":"Luke","chapter":8,"mood":"dark","order":27,"durationSeconds":54},
  {"id":"dorcas-needle","cardTitle":"The Coats She Made","heat":1,"badge":"Today's tea","hook":"There is exactly one woman in the whole New Testament that Luke calls a disciple. She spent her life sewing.","tea":"Joppa. Her name is Tabitha. In Greek, Dorcas. Luke describes her in one line. \"Full of good works and almsdeeds which she did.\" Not that she was kind. What she did. Then she dies. They wash her. Carry her upstairs. The disciples hear Peter is one town over and send two men, begging. Come. Do not wait. He comes. They take him upstairs. And this is the part. \"All the widows stood by him weeping, and shewing the coats and garments which Dorcas made, while she was with them.\" They are holding up the clothes. That is the eulogy. Not words. Evidence. Understand what a widow was then. No income. No safety net. This woman had quietly been dressing them. Now watch Peter. \"But Peter put them all forth, and kneeled down, and prayed.\" Put them all forth. Years earlier, Peter was one of three men Jesus let into a room with a dead girl. Mark says Jesus \"put them all out.\" Knelt. And said, \"Talitha cumi.\" Peter clears the room the same way. And says, \"Tabitha, arise.\" One letter apart. He was in the room the day he learned how to do that.","ref":"Acts 9:39","book":"Acts","chapter":9,"mood":"light","order":28,"durationSeconds":77},
  {"id":"phoebe-letter","cardTitle":"A Succourer Of Many","heat":2,"badge":"Receipts","hook":"Girl, pause the scroll… Paul is finishing Romans and casually name-drops her like it is nothing… …","tea":"Phoebe. Romans sixteen, the final chapter. \"I commend unto you Phebe our sister, which is a servant of the church which is at Cenchrea.\" That word servant is diakonos in the Greek, the same word rendered deacon and minister elsewhere in the New Testament. Which one it means here is a translation call, not a settled fact. Then Paul tells an entire church what to do about her. \"That ye receive her in the Lord, as becometh saints, and that ye assist her in whatsoever business she hath need of you.\" Whatever she needs. Give it to her. And then the line that lands. \"For she hath been a succourer of many, and of myself also.\" A patron. A protector. She is the one who showed up with cover and connections, and Paul is saying he was one of the people she showed up for. She is commended first, right at the front of the chapter, which is why so many believe she is the one who carried the letter to Rome. That part is inference, not chapter and verse. What is chapter and verse is that Paul made sure nobody got to treat her like a side character.","ref":"Romans 16:1","book":"Romans","chapter":16,"mood":"dark","order":29,"durationSeconds":60},
  {"id":"mary-perfume","cardTitle":"A Year Poured Out","heat":3,"badge":"Wild","hook":"Okay bestie, the drama… she poured a year of wages on the floor and the man complaining was stealing… …","tea":"Bethany, six days before the Passover. \"Then took Mary a pound of ointment of spikenard, very costly, and anointed the feet of Jesus, and wiped his feet with her hair: and the house was filled with the odour of the ointment.\" Everybody in that room knows exactly what it cost, because they can smell it. Then Judas objects, and he uses the language of charity. \"Why was not this ointment sold for three hundred pence, and given to the poor?\" Three hundred pence. A penny is a day's wage elsewhere in the Gospels, so that is roughly a year of work, poured out on the floor. And John tells you his motive outright. \"This he said, not that he cared for the poor; but because he was a thief, and had the bag, and bare what was put therein.\" The man doing the maths on her devotion was skimming the fund. And Jesus shuts it down in the room. \"Let her alone: against the day of my burying hath she kept this.\" She understood the assignment while the men were still doing arithmetic.","ref":"John 12:7","book":"John","chapter":12,"mood":"light","order":30,"durationSeconds":58},
];

let catalogCache = null;
let todayCache = null;

/** First 4 words of the hook, only ever used if a card somehow ships untitled. */
function fallbackCardTitle(t) {
  const src = (t.hook || t.tea || '').replace(/["“”]/g, '').trim();
  if (!src) return 'Today’s tea';
  return src.split(/\s+/).slice(0, 4).join(' ').replace(/[.,;:!?]$/, '');
}

function normalize(t) {
  return {
    ...t,
    // Server-provided title wins; the derived one is a safety net, not the plan.
    cardTitle: t.cardTitle || fallbackCardTitle(t),
    likes: t.likes ?? 0,
    heat: t.heat ?? 1,
    durationSeconds: t.durationSeconds ?? 62,
    image: t.image ?? `/img/tea/${t.id}.jpg`,
    audioUrl: t.audioUrl ?? `/audio/tea-${t.id}.mp3`,
    hasAudio: true,
  };
}

async function loadCatalog() {
  if (catalogCache) return catalogCache;
  try {
    const { data } = await api.get('/tea', { auth: false });
    const tea = (data.tea || []).map(normalize);
    catalogCache = tea.length ? tea : FALLBACK_TEAS.map(normalize);
    await StorageService.set(KEYS.teaCatalog, catalogCache);
  } catch {
    // Prefer the last catalog we actually saw over the bundled copy.
    const cached = await StorageService.get(KEYS.teaCatalog, null);
    catalogCache = (cached && cached.length ? cached : FALLBACK_TEAS).map(normalize);
  }
  return catalogCache;
}

/** Same rule the server uses, so offline picks the same tea as online. */
function localTeaOfDay(all) {
  const day = Math.floor(Date.now() / 86400000);
  const ordered = [...all].sort((a, b) => a.order - b.order);
  return ordered[((day % ordered.length) + ordered.length) % ordered.length];
}

export const TeaService = {
  async getToday({ force = false } = {}) {
    if (todayCache && !force) return todayCache;
    try {
      const { data } = await api.get('/tea/today', { auth: false });
      todayCache = normalize(data.tea);
    } catch {
      todayCache = localTeaOfDay(await loadCatalog());
    }
    return todayCache;
  },
  async getAll() {
    return loadCatalog();
  },
  async refresh() {
    catalogCache = null;
    todayCache = null;
    const [today, all] = [await this.getToday({ force: true }), await this.getAll()];
    return { today, all };
  },
  /**
   * The render's own transcript with word timings, used to drive live captions.
   * Cached so captions still work offline after one view. Null when the clip has
   * no sidecar, in which case the caller shows static copy rather than captions
   * that would drift out of sync.
   */
  async getTranscript(id) {
    const cache = await StorageService.get(KEYS.transcripts, {});
    const key = `tea#${id}`;
    try {
      const { data } = await api.get(`/tea/${encodeURIComponent(id)}/transcript`, { auth: false });
      cache[key] = data;
      await StorageService.set(KEYS.transcripts, cache);
      return data;
    } catch {
      return cache[key] || null;
    }
  },
  async getOne(id) {
    try {
      const { data } = await api.get(`/tea/${encodeURIComponent(id)}`, { auth: false });
      return normalize(data);
    } catch {
      const local = (await loadCatalog()).find((t) => t.id === id);
      return local || null;
    }
  },
  async toggleLike(id) {
    const saved = await StorageService.get(KEYS.teaEngagement, {});
    const next = { ...(saved[id] || {}), liked: !saved[id]?.liked };
    saved[id] = next;
    await StorageService.set(KEYS.teaEngagement, saved);
    try {
      await AuthService.ensureGuest();
      await api.post(`/tea/${encodeURIComponent(id)}/like`);
    } catch { /* offline, local only */ }
    return next;
  },
  async save(id) {
    const saved = await StorageService.get(KEYS.teaEngagement, {});
    const next = { ...(saved[id] || {}), saved: !saved[id]?.saved };
    saved[id] = next;
    await StorageService.set(KEYS.teaEngagement, saved);
    try {
      await AuthService.ensureGuest();
      await api.post(`/tea/${encodeURIComponent(id)}/save`);
    } catch { /* offline, local only */ }
    return next;
  },
  async getEngagement(id) {
    const saved = await StorageService.get(KEYS.teaEngagement, {});
    return saved[id] || { liked: false, saved: false };
  },
  async getSaved() {
    const saved = await StorageService.get(KEYS.teaEngagement, {});
    const all = await loadCatalog();
    return all.filter((t) => saved[t.id]?.saved);
  },
};
