// Reads backend/src/lib/teaCatalog.ts and emits the offline fallback bundle
// consumed by the Expo app so TeaService cannot drift from the API catalog.
//
//   npm run sync:tea-fallback
import { writeFile } from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import { TEAS, teaForClient } from '../src/lib/teaCatalog.js';

const here = path.dirname(fileURLToPath(import.meta.url));
const outPath = path.join(here, '../../src/services/teaFallback.generated.js');

async function main() {
  const teas = [...TEAS].sort((a, b) => a.order - b.order).map(teaForClient);
  const body = `// AUTO-GENERATED by backend/scripts/sync-tea-fallback.ts — do not edit manually.
// Regenerate after teaCatalog.ts changes: cd backend && npm run sync:tea-fallback

export const FALLBACK_TEAS = ${JSON.stringify(teas, null, 2)};
`;
  await writeFile(outPath, body);
  console.log(`✓ wrote ${teas.length} teas to ${outPath}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
