// Tea — a daily sermon. One ~60 second clip a day, with a scrollable archive of
// 30 to start. Sassy, modern, reverent. Copy is deliberately bold but never
// mocks Scripture; product/theology review before ship.
//
// House style: no em-dashes anywhere in this file's user-facing copy. Use a
// comma, a period, or "and".
export type Tea = {
  id: string;
  hook: string; // the shareable serif line
  tea: string; // 2 to 3 punchy sentences, ~60s narrated
  badge: string; // "Today's tea" | 'Plot twist' | 'Hot take' | 'Receipts' | 'Wild'
  ref: string;
  book: string;
  chapter: number;
  mood: 'dark' | 'light';
  /** 1 warm, 2 spicy, 3 wild. Drives the badge + card treatment. */
  heat: 1 | 2 | 3;
  likes: number;
  order: number;
  /** '/img/tea/<id>.jpg' — served by the static image route once art lands. */
  image?: string | null;
  audioUrl?: string | null; // '/audio/tea-<id>.mp3' (~60s)
  durationSeconds?: number; // 55 to 70
  voice?: string | null; // optional per-card ElevenLabs voice override
};

/** Default template: pre-rendered static MP3 per tea, served by /audio/:filename. */
const TEA_AUDIO_URL = '/audio/tea-{teaId}.mp3';

type TeaSeed = Omit<Tea, 'likes' | 'image' | 'audioUrl' | 'durationSeconds'> & {
  likes?: number;
  image?: string | null;
  audioUrl?: string | null;
  durationSeconds?: number;
};

const SEED: TeaSeed[] = [
  { id: 'vashti-no', durationSeconds: 52, heat: 2, badge: "Today's tea", hook: 'Vashti said no to the king and kept her crown out of it.', tea: 'Picture it. Day seven of a royal drinking festival, and the king\'s heart is merry with wine. He sends seven of his chamberlains to fetch Queen Vashti, so the princes and the people can look at her, because the text says she was fair to look on. And Vashti says no. She refuses to come. Now, Scripture does not tell us why. It records her refusal and not her reasoning, so anyone who tells you exactly what she was thinking is filling in a blank. What we do get is the reaction. The king is furious. His advisers panic, and one of them stands up and says, in effect, if this gets out, every woman in the empire will hear about it and start answering back. So they write a law. They take her royal estate and give it to another. They send letters into every province, in every language, saying that every man should bear rule in his own house. That is how threatened they were. One woman said one word, and an empire wrote legislation about it.', ref: 'Esther 1:12', book: 'Esther', chapter: 1, mood: 'dark', order: 1 },
  { id: 'ruth-field', durationSeconds: 57, heat: 1, badge: 'Plot twist', hook: 'Ruth rewrote her whole story in a barley field.', tea: 'Widowed, broke, and foreign. Her mother in law Naomi told her twice to go home to Moab, and Ruth said no. Whither thou goest, I will go. Thy people shall be my people, and thy God my God. Then they walk into Bethlehem with nothing, right at the start of barley harvest. And Ruth goes to work. The law said harvesters could not strip a field clean, so the poor were allowed to follow the reapers and pick up what fell. That is what she does. She asks to glean, and the text says her hap was to light on a field belonging to Boaz, a relative of her late husband\'s family. Her happenstance. Sure. Boaz notices her, tells his men not to touch her, tells her to drink their water, and quietly orders them to drop extra grain where she will find it. She goes home with about an ephah of barley. A few chapters later, Boaz redeems the family line at the town gate, and Ruth has a son named Obed. Obed\'s grandson is King David. Loyalty is a flex.', ref: 'Ruth 2:2', book: 'Ruth', chapter: 2, mood: 'light', order: 2 },
  { id: 'deborah-palm', durationSeconds: 48, heat: 2, badge: 'Receipts', hook: 'Deborah ran a nation from under a palm tree.', tea: 'Judges chapter four. Deborah is a prophetess, and she is judging Israel at the time, and she holds court under a palm tree between Ramah and Bethel. The children of Israel come up to her for judgement. That is her office. That is her authority, written down, no hedging. So she summons Barak and gives him God\'s orders. Take ten thousand men to mount Tabor. I will draw out Sisera and his chariots to the river Kishon and deliver him into thine hand. And Barak, the military commander, says, if thou wilt go with me, then I will go. But if thou wilt not go with me, then I will not go. He will not move without her. So she goes. And she tells him plainly, the journey that thou takest shall not be for thine honour, for the Lord shall sell Sisera into the hand of a woman. She called the ending before it happened, and it landed exactly the way she said. She held court under a tree, and the nation came to her.', ref: 'Judges 4:4', book: 'Judges', chapter: 4, mood: 'dark', order: 3 },
  { id: 'abigail-intercept', durationSeconds: 63, heat: 2, badge: 'Hot take', hook: 'Abigail stopped a war with supplies and a speech.', tea: 'First Samuel twenty five. David\'s men had protected Nabal\'s shepherds, and when David sends ten young men to ask for provision, Nabal insults him and sends them away with nothing. David straps on his sword and takes four hundred men. He is riding out to wipe out a household. A servant runs to Abigail and tells her everything. And she does not call a meeting. The text says she made haste. Two hundred loaves, two bottles of wine, five dressed sheep, roasted grain, a hundred clusters of raisins, two hundred cakes of figs. She loads it all onto donkeys and rides out to intercept an armed column, without telling her husband. Then she gets down off the donkey, falls on her face, and talks. She takes the blame on herself, tells David that shedding this blood would be a grief and an offence of heart to him later, and asks him to remember her when God has done him good. And David says, blessed be thy advice, and blessed be thou, which hast kept me this day from coming to shed blood. She talked a future king off the ledge.', ref: '1 Samuel 25:18', book: '1 Samuel', chapter: 25, mood: 'light', order: 4 },
  { id: 'mary-yes', durationSeconds: 54, heat: 1, badge: "Today's tea", hook: 'She said yes to the impossible, and the world turned.', tea: 'Luke chapter one. Gabriel is sent to Nazareth, to a virgin espoused to a man named Joseph, and her name is Mary. Note what Luke tells us and what he does not. He gives us the town, the man she is promised to, his royal line. He never gives us her age. So when you hear her called a teenager, that is tradition talking, not the text. The angel says, Hail, thou that art highly favoured, the Lord is with thee. And she is troubled. Not by the angel. By the greeting. She is turning the words over, wondering what kind of salutation this is. Then the news. You will conceive and bear a son, and call his name Jesus, and his kingdom will have no end. She asks one practical question. How shall this be, seeing I know not a man? She is not asking for proof. She is asking how. And when the answer comes, she says, Behold the handmaid of the Lord, be it unto me according to thy word. She said yes to a plan she could not verify, in a village that could count.', ref: 'Luke 1:38', book: 'Luke', chapter: 1, mood: 'dark', order: 5 },
  { id: 'martha-mary', durationSeconds: 51, heat: 1, badge: 'Plot twist', hook: 'Mary ignored the whole room and chose the moment.', tea: 'Luke chapter ten. Jesus comes into a village, and a woman named Martha receives him into her house. Her sister Mary sits down at his feet and listens to what he is saying. And Martha is cumbered about much serving. The word carries the sense of being pulled in every direction. She is doing real work, and nobody is helping, and eventually she does what a lot of us do. She takes it to Jesus and makes it his problem. Lord, dost thou not care that my sister hath left me to serve alone? Bid her therefore that she help me. And she is not wrong that she is alone. Look at his answer, because it is gentler than people make it sound. Martha, Martha, thou art careful and troubled about many things. He says her name twice. That is not a scolding, that is tenderness. But one thing is needful, and Mary hath chosen that good part, which shall not be taken away from her. He does not tell Mary to get up. He tells Martha she is allowed to sit down.', ref: 'Luke 10:42', book: 'Luke', chapter: 10, mood: 'light', order: 6 },
  { id: 'well-woman', durationSeconds: 55, heat: 3, badge: 'Wild', hook: 'The woman at the well came for water and left a preacher.', tea: 'John chapter four. Jesus is tired from the journey and sits down by Jacob\'s well, and it is about the sixth hour, so around midday. A woman of Samaria comes to draw water, and he asks her for a drink. Which is already a scandal on two counts, because Jews had no dealings with Samaritans, and she says so to his face. Then the conversation turns. He offers her living water. She wants it. He says, go call thy husband. And she says, I have no husband. And he tells her, you have said well, for thou hast had five husbands, and he whom thou now hast is not thy husband. People often say she came at noon to avoid the gossip. That is a reasonable guess, and it is a guess. What the text actually says is that she left her waterpot, went back into the city, and said, come, see a man which told me all things that ever I did. And many of the Samaritans of that city believed on him because of her word. She dropped the jar and became the testimony.', ref: 'John 4:28', book: 'John', chapter: 4, mood: 'dark', order: 7 },
  { id: 'esther-uninvited', durationSeconds: 62, heat: 2, badge: 'Hot take', hook: 'Esther walked in uninvited and saved a nation.', tea: 'Approaching the Persian king without a summons carried one penalty, and the whole empire knew it. Death. The one exception was if he held out the golden sceptre. And Esther tells Mordecai, I have not been called to come in unto the king these thirty days. She is the queen and she has not been summoned in a month. Mordecai\'s answer is brutal and kind at once. Do not think you will escape in the king\'s house any more than the rest of the Jews. And then, if you hold your peace, deliverance will arise from another place, but you and your father\'s house will be destroyed. He never says God will fail. He says rescue is coming and she might miss it. Then, who knoweth whether thou art come to the kingdom for such a time as this? A question, not a command. So she fasts three days with all the Jews in Shushan, and says, if I perish, I perish. On the third day she puts on her royal apparel and stands in the inner court. And the king holds out the sceptre. She lives. And then she throws the dinner party that flipped an empire.', ref: 'Esther 4:16', book: 'Esther', chapter: 4, mood: 'light', order: 8 },
  { id: 'hannah-prayer', durationSeconds: 51, heat: 1, badge: "Today's tea", hook: 'Hannah prayed so hard the priest thought she was drunk.', tea: 'First Samuel chapter one. Hannah is one of two wives, and she has no children, and Peninnah, the one with children, provokes her about it. The text calls Peninnah her adversary, and says this happened year after year, every time they went up to the house of the Lord. So Hannah stops eating and she weeps. Her husband Elkanah loves her, and he says the most well meaning wrong thing in Scripture. Am not I better to thee than ten sons? Then she gets up from the table and goes to the temple, and she prays in bitterness of soul. And here is the detail. She spake in her heart, only her lips moved, but her voice was not heard. Eli the priest is watching her mouth, and he decides she is drunk, and he says so out loud. Put away thy wine from thee. And Hannah does not shrink and she does not fight. No, my lord. I am a woman of a sorrowful spirit. I have poured out my soul before the Lord. She was the most honest person in that building, and the professional called her a drunk.', ref: '1 Samuel 1:13', book: '1 Samuel', chapter: 1, mood: 'dark', order: 9 },
  { id: 'magdalene-first', durationSeconds: 62, heat: 2, badge: 'Receipts', hook: 'Mary Magdalene was the first to preach the resurrection.', tea: 'John chapter twenty. She comes to the tomb while it is still dark, sees the stone taken away, and runs to Peter and John. They race back, look inside, see the linen clothes, and then the text says they went away again unto their own home. She does not. Mary stood without at the sepulchre weeping. Everyone else left. She stayed and cried in a graveyard. So she is the one who is there when two angels ask why she is weeping, and she is the one who turns around and sees him standing there, and supposes him to be the gardener. Sir, she says, if thou have borne him hence, tell me where thou hast laid him, and I will take him away. She is grieving and she is still trying to do the practical thing. And he says one word. Mary. And she knows. Then he sends her. Go to my brethren, and say unto them, I ascend unto my Father. And Mary Magdalene came and told the disciples that she had seen the Lord. The whole faith starts with a woman running with news.', ref: 'John 20:18', book: 'John', chapter: 20, mood: 'light', order: 10 },
  { id: 'rahab-rope', durationSeconds: 52, heat: 3, badge: 'Wild', hook: 'Rahab ran a safe house and negotiated her family out of a war.', tea: 'Joshua chapter two. Two spies come into Jericho and lodge at the house of a harlot named Rahab. The king hears about it and sends word to bring them out. And Rahab hides them under stalks of flax on her roof, then tells the messengers the men have already left and if they hurry they will catch them. The text records what she said, plainly, without softening it. Then she goes up to the roof and tells the spies the real reason. We have heard what your God did at the Red Sea. Our hearts did melt. The Lord your God, he is God in heaven above, and in earth beneath. So she cuts a deal, and notice she does not negotiate for herself alone. Save my father, and my mother, and my brethren, and my sisters, and all that they have. They tell her to bind a line of scarlet thread in the window. Her house is on the town wall, and she lets them down by a cord. Jericho falls and her whole household lives. And Matthew\'s genealogy puts her in the family line of Jesus.', ref: 'Joshua 2:4', book: 'Joshua', chapter: 2, mood: 'dark', order: 11 },
  { id: 'jael-tent', durationSeconds: 51, heat: 3, badge: 'Wild', hook: 'Jael ended a war with a tent peg and a bottle of milk.', tea: 'Judges chapter four. Sisera is the commander of nine hundred iron chariots, and he has just watched his entire army fall to Barak. So he runs. On foot. And he runs to the tent of Jael, wife of Heber the Kenite, because there was peace between his king and that household. He thinks he has found a neutral corner. Jael goes out to meet him and says, turn in, my lord, turn in to me, fear not. He comes in. She covers him with a mantle. He asks for a little water, and she opens a bottle of milk and gives him a drink, and covers him again. Then he tells her to stand in the door, and if anyone asks whether a man is there, say no. So he sleeps. The text says he was fast asleep and weary. And Jael takes a nail of the tent and a hammer, and goes softly, and it is finished. Then she walks out and shows Barak the body. Deborah\'s song in the next chapter calls her blessed above women in the tent. Scripture does not soften this one, and neither will I.', ref: 'Judges 4:21', book: 'Judges', chapter: 4, mood: 'dark', order: 12 },
  { id: 'tamar-veil', durationSeconds: 62, heat: 3, badge: 'Wild', hook: 'Tamar outmaneuvered a patriarch and got it in writing.', tea: 'Genesis thirty eight, and it is a rough chapter. Tamar is married to Judah\'s eldest son, who dies. By custom she is given to the next brother, who also dies. Judah tells her to go live as a widow in her father\'s house until his third son grows up, and then he never sends for him. So she is left in limbo, no husband, no children, no standing, and no way to challenge it. Then she hears Judah is going up to Timnath to shear sheep. She takes off her widow\'s clothes, covers herself with a veil, and sits by the road. He does not recognise her. He propositions her, and promises a kid from the flock. And this is where she gets sharp. She asks for a pledge first. His signet, his bracelets, and his staff. His identification, essentially. Three months later, she is pregnant, and Judah is told, and he says bring her out and let her be burnt. And she sends him his own signet and staff and says, discern whose these are. And Judah says, she hath been more righteous than I.', ref: 'Genesis 38:26', book: 'Genesis', chapter: 38, mood: 'light', order: 13 },
  { id: 'miriam-song', durationSeconds: 56, heat: 1, badge: 'Plot twist', hook: 'Miriam grabbed a timbrel at the edge of a dry sea.', tea: 'Exodus fifteen. Israel has just walked through the sea on dry ground and watched the water close behind them. And Moses and the children of Israel sing first. That is the order in the text, and it matters, so let us keep it straight. Then verse twenty. And Miriam the prophetess, the sister of Aaron, took a timbrel in her hand, and all the women went out after her with timbrels and with dances. And Miriam answered them, sing ye to the Lord, for he hath triumphed gloriously, the horse and his rider hath he thrown into the sea. She answered them. She takes the song and she leads the women in it, with percussion and dancing, on the far shore of an impossible crossing. Two things Scripture calls her right there. Prophetess. And sister of Aaron. Exodus two does not name the sister who watched the basket in the reeds, though Numbers twenty six names Miriam among those siblings, and that is the connection most readers make. What is certain is this. When the water closed, she picked up an instrument.', ref: 'Exodus 15:20', book: 'Exodus', chapter: 15, mood: 'light', order: 14 },
  { id: 'shunammite', durationSeconds: 51, heat: 2, badge: 'Receipts', hook: 'The Shunammite woman refused to leave without an answer.', tea: 'Second Kings chapter four. This woman is described as great, meaning of standing, and she is the one who notices Elisha passing through and builds him a room on the wall with a bed, a table, a stool and a candlestick. She asks for nothing. Elisha wants to repay her and she says, I dwell among mine own people. She is fine. He gives her a son anyway. Then years later the boy is out in the field with the reapers, says my head, my head, and is carried to his mother. He sat on her knees till noon, and then died. And watch what she does. She carries him upstairs, lays him on the prophet\'s bed, shuts the door, and saddles a donkey. She does not tell her husband what has happened. She rides to mount Carmel. Elisha\'s servant tries to intercept her, and she pushes past him. She catches Elisha by the feet, and when the servant moves to shove her away, Elisha says, let her alone, for her soul is vexed within her. And she will not go home without him. Faith can look like refusing to be managed.', ref: '2 Kings 4:30', book: '2 Kings', chapter: 4, mood: 'dark', order: 15 },
  { id: 'widow-oil', durationSeconds: 61, heat: 1, badge: "Today's tea", hook: 'A widow with one jar of oil out-earned her debt.', tea: 'Second Kings four, opening scene. A woman comes to Elisha crying, and her situation is this. Her husband is dead, he feared the Lord, and the creditor is coming to take her two sons to be bondmen. Not the furniture. The children. That is the debt system she is trapped in. Elisha asks her, what shall I do for thee? Tell me, what hast thou in the house? And she says, thine handmaid hath not any thing in the house, save a pot of oil. One pot. That is the whole inventory. And he tells her, go borrow thee vessels abroad of all thy neighbours, even empty vessels. Borrow not a few. Then shut the door on yourself and your sons, and start pouring. So she does. And the oil keeps coming. Vessel after vessel, until she says to her son, bring me yet a vessel, and he says, there is not a vessel more. And the oil stayed. She sells it, pays the debt, and lives on the rest. The supply stopped exactly when the containers did.', ref: '2 Kings 4:6', book: '2 Kings', chapter: 4, mood: 'light', order: 16 },
  { id: 'bleeding-woman', durationSeconds: 54, heat: 2, badge: 'Hot take', hook: 'She touched his coat in a crowd and stopped the whole procession.', tea: 'Mark chapter five. Twelve years of bleeding. And Mark, who was not gentle about it, says she had suffered many things of many physicians, and had spent all that she had, and was nothing bettered, but rather grew worse. Every doctor paid. Every option gone. Worse than when she started. Then she hears about Jesus. And she does not go to the front and ask. She comes up behind him in the press of the crowd, because she says within herself, if I may touch but his clothes, I shall be whole. And she does. And straightway the fountain of her blood was dried up. And here is the part that always gets me. He stops. In a crowd pressing in on him from every side, he turns around and asks who touched my clothes. His disciples think that is an absurd question. But he keeps looking. And she comes fearing and trembling, and falls down, and tells him all the truth. Not a summary. All of it. And he says, daughter, thy faith hath made thee whole. Go in peace. He would not let her leave as a secret.', ref: 'Mark 5:34', book: 'Mark', chapter: 5, mood: 'dark', order: 17 },
  { id: 'canaanite-mother', durationSeconds: 54, heat: 3, badge: 'Wild', hook: 'A foreign mother argued with Jesus and won.', tea: 'Matthew fifteen. Jesus goes into the coasts of Tyre and Sidon, and a woman of Canaan comes out crying after him. Have mercy on me, O Lord, thou son of David, my daughter is grievously vexed with a devil. And he answered her not a word. The disciples want her sent away because she keeps crying after them. Then he says he was sent to the lost sheep of the house of Israel. She comes and worships him and says three words. Lord, help me. And he gives her the hard line. It is not meet to take the children\'s bread, and to cast it to dogs. Now, people argue about the tone of that sentence, and the text does not give us tone, so hold your theory loosely. What is not in dispute is her answer. Truth, Lord, yet the dogs eat of the crumbs which fall from their masters\' table. She takes his metaphor, accepts the terms, and turns it. And he says, O woman, great is thy faith. Be it unto thee even as thou wilt. And her daughter was made whole from that very hour.', ref: 'Matthew 15:28', book: 'Matthew', chapter: 15, mood: 'light', order: 18 },
  { id: 'anna-temple', durationSeconds: 52, heat: 1, badge: 'Plot twist', hook: 'Anna waited decades in the temple for one look.', tea: 'Luke chapter two. Anna is a prophetess, daughter of Phanuel, of the tribe of Aser. Luke says she was of a great age, and had lived with a husband seven years from her virginity, and was a widow of about fourscore and four years. Translators split on that last phrase. It either means she was eighty four years old, or that she had been a widow for eighty four years. Either reading is a very long wait, and honest teachers say so rather than picking whichever number preaches better. What is not ambiguous is how she spent it. She departed not from the temple, but served God with fastings and prayers night and day. And then a poor couple walks in with a newborn to do what the law required, and Anna comes in that instant. She gives thanks to God, and she spake of him to all them that looked for redemption in Jerusalem. Decades of showing up, and she recognised him immediately, and she started telling everybody. Patience is not passivity.', ref: 'Luke 2:38', book: 'Luke', chapter: 2, mood: 'dark', order: 19 },
  { id: 'lydia-house', durationSeconds: 54, heat: 2, badge: 'Receipts', hook: 'Lydia heard one sermon by a river and bankrolled the mission.', tea: 'Acts sixteen. Paul and his companions arrive in Philippi, and on the sabbath they go out of the city by a river side, where prayer was customarily made. They sit down and speak to the women who gathered there. And a certain woman named Lydia heard them. She is a seller of purple from the city of Thyatira, which is the luxury goods trade of the ancient world, and she worshipped God. And the text says the Lord opened her heart, that she attended unto the things which were spoken of Paul. She is baptized, and her household with her. And then she makes an offer that is really not an offer. If ye have judged me to be faithful to the Lord, come into my house, and abide there. And the text adds four words. And she constrained us. She talked them into it. Later in the chapter, after Paul and Silas get out of prison, where do they go? They entered into the house of Lydia. Her house was the base. Not asked. Told.', ref: 'Acts 16:15', book: 'Acts', chapter: 16, mood: 'light', order: 20 },
  { id: 'priscilla-teach', durationSeconds: 54, heat: 2, badge: 'Hot take', hook: 'Priscilla corrected a famous preacher in private.', tea: 'Acts eighteen. A man named Apollos comes to Ephesus. Born at Alexandria, eloquent, mighty in the scriptures, fervent in spirit. He teaches diligently the things of the Lord. And then the text adds one qualifier that changes everything. Knowing only the baptism of John. He is brilliant and he is behind. So he starts speaking boldly in the synagogue. And Aquila and Priscilla hear him. And they do not stand up and correct him in front of the room. Whom when Aquila and Priscilla had heard, they took him unto them, and expounded unto him the way of God more perfectly. They took him aside. They filled in what was missing. That is the whole move. Afterwards Apollos goes on to Achaia with a letter of recommendation from the believers, and he helps them much, and mightily convinces the Jews publicly. Small note that readers have made much of. In several places her name is listed first, including here. Luke never tells us why, so treat the theories as theories. What we can see is that she taught the teacher.', ref: 'Acts 18:26', book: 'Acts', chapter: 18, mood: 'dark', order: 21 },
  { id: 'sarah-laugh', durationSeconds: 69, heat: 2, badge: 'Plot twist', hook: 'Sarah laughed at God and still got the promise.', tea: 'Genesis eighteen. Three visitors come to Abraham\'s tent in the heat of the day. He runs to meet them, hurries Sarah into making bread, and has a calf dressed. Then one of them says, I will certainly return unto thee according to the time of life, and lo, Sarah thy wife shall have a son. And Sarah is listening at the tent door behind him. The text is blunt about the situation. Abraham and Sarah were old and well stricken in age, and it ceased to be with Sarah after the manner of women. So she laughed within herself. Not out loud. Within herself. And she says, after I am waxed old shall I have pleasure, my lord being old also? And the Lord says to Abraham, wherefore did Sarah laugh? Is any thing too hard for the Lord? Then she is afraid, and she denies it. Nay, I laughed not. And he says, plainly, Nay, but thou didst laugh. He does not withdraw the promise. Genesis twenty one, she has the boy, and she names him Isaac, which means laughter, and she says God hath made me to laugh.', ref: 'Genesis 18:12', book: 'Genesis', chapter: 18, mood: 'light', order: 22 },
  { id: 'hagar-seen', durationSeconds: 52, heat: 2, badge: "Today's tea", hook: 'Hagar named God herself, out loud, in the desert.', tea: 'Genesis sixteen. Hagar is Sarai\'s Egyptian handmaid, and she is given to Abram, and when she conceives, the text says her mistress was despised in her eyes, and Sarai deals harshly with her. So Hagar runs. Pregnant, alone, into the wilderness. And the angel of the Lord finds her by a fountain of water in the wilderness, by the way to Shur. And he calls her by name and by station. Hagar, Sarai\'s maid, whence camest thou? And whither wilt thou go? Two questions. Where have you come from, and where are you going. She answers only the first one, because she does not have an answer to the second. Then she is told she will bear a son, and to call his name Ishmael, because the Lord hath heard thy affliction. And then she does something that, as far as the text shows us, nobody in Scripture had done before her. She calls the name of the Lord that spake unto her, Thou God seest me. She names God. A runaway foreign slave woman in a desert, and she is the one who gets to say it.', ref: 'Genesis 16:13', book: 'Genesis', chapter: 16, mood: 'dark', order: 23 },
  { id: 'zelophehad', durationSeconds: 62, heat: 3, badge: 'Wild', hook: 'Five sisters sued for their inheritance and changed the law.', tea: 'Numbers twenty seven. Their names are Mahlah, Noah, Hoglah, Milcah and Tirzah, and Scripture lists every one. Their father Zelophehad died in the wilderness, and he had no sons. Under the inheritance rules as they stood, land passed through sons, so his name and his portion would simply vanish. So the five of them go and stand before Moses, and before Eleazar the priest, and before the princes, and before all the congregation, at the door of the tabernacle. That is the entire leadership of the nation and the whole assembly, and five women walk up and make a legal argument. Why should the name of our father be done away from among his family, because he hath no son? Give unto us a possession among the brethren of our father. And Moses does not rule on it. He brought their cause before the Lord. And the Lord said unto Moses, the daughters of Zelophehad speak right. Thou shalt surely give them a possession of an inheritance. God agreed with them, on the record, and the law of inheritance was rewritten because five sisters asked.', ref: 'Numbers 27:7', book: 'Numbers', chapter: 27, mood: 'light', order: 24 },
  { id: 'huldah-scroll', durationSeconds: 56, heat: 2, badge: 'Receipts', hook: 'When a lost scroll turned up, the king sent for Huldah.', tea: 'Second Kings twenty two. They are renovating the temple, paying the carpenters and the builders, and during the works Hilkiah the high priest finds the book of the law. Shaphan the scribe reads it to King Josiah, and the king tears his clothes, because he realises how far the nation has drifted from what is written in it. So he needs a ruling. Enquire of the Lord for me, he says, and for the people, and for all Judah, concerning the words of this book that is found. Now think about who is available. He has a high priest. He has a scribe. He has a whole religious establishment on payroll. And they go to Huldah the prophetess, who lived in Jerusalem in the college. Five men, sent by a king, to a woman, for the authoritative reading. And she does not soften it. She sends back judgement on the nation, and mercy for Josiah personally, because his heart was tender. Her reading became national policy. The reformation that follows in the next chapter runs on what she said.', ref: '2 Kings 22:14', book: '2 Kings', chapter: 22, mood: 'dark', order: 25 },
  { id: 'widow-mite', durationSeconds: 53, heat: 1, badge: 'Plot twist', hook: 'She gave two coins and out-gave the entire treasury.', tea: 'Mark twelve. Jesus sat over against the treasury, and beheld how the people cast money into the treasury. That is the setup. He sat down and watched people give. And many that were rich cast in much. Then comes a certain poor widow, and she throws in two mites, which make a farthing. Mark actually converts the currency for his readers, which tells you how small it was. And Jesus calls his disciples over, because he wants them to see this specifically. Verily I say unto you, that this poor widow hath cast more in, than all they which have cast into the treasury. More than all of them. And then he does the maths out loud. For all they did cast in of their abundance, but she of her want did cast in all that she had, even all her living. All her living. Not a percentage. The whole thing. He is not measuring the gift. He is measuring what was left afterwards.', ref: 'Mark 12:44', book: 'Mark', chapter: 12, mood: 'light', order: 26 },
  { id: 'joanna-fund', durationSeconds: 50, heat: 2, badge: 'Hot take', hook: 'Wealthy women funded the entire ministry.', tea: 'Luke chapter eight, and it is three verses that get skipped constantly. Jesus is going throughout every city and village preaching, and the twelve are with him. And then Luke says, and certain women, which had been healed of evil spirits and infirmities. He names them. Mary called Magdalene, out of whom went seven devils. And Joanna the wife of Chuza, Herod\'s steward. Stop on that one. Herod\'s steward. That is a household manager inside the royal court, which means Joanna had access and money and a great deal to lose. And Susanna. And many others. And then the line. Which ministered unto him of their substance. Their substance. Their own resources. The most famous ministry in history was underwritten by a group of women, one of them connected to the court of the king who had John the Baptist killed. Luke names them on purpose. He did not have to. He wanted somebody three thousand years later to know exactly who paid for it.', ref: 'Luke 8:3', book: 'Luke', chapter: 8, mood: 'dark', order: 27 },
  { id: 'dorcas-needle', durationSeconds: 59, heat: 1, badge: "Today's tea", hook: 'Dorcas sewed so much love that the widows brought the evidence.', tea: 'Acts nine. In Joppa there is a disciple named Tabitha, which by interpretation is Dorcas, and the text says she was full of good works and almsdeeds which she did. Then she gets sick and she dies. They wash her and lay her in an upper chamber. Lydda is near Joppa, and the disciples hear Peter is there, so they send two men asking him to come without delay. And when Peter arrives, they bring him upstairs into that room. And here is the scene. All the widows stood by him weeping, and shewing the coats and garments which Dorcas made, while she was with them. They are holding up the clothes. That is the eulogy. Not a speech. Evidence. Widows in that world had almost no safety net, and she had been making them clothes with her own hands. Peter puts them all out of the room, kneels down, prays, turns to the body and says, Tabitha, arise. And she opened her eyes, and sat up. And he called the saints and widows and presented her alive.', ref: 'Acts 9:39', book: 'Acts', chapter: 9, mood: 'light', order: 28 },
  { id: 'phoebe-letter', durationSeconds: 53, heat: 2, badge: 'Receipts', hook: 'Paul told a whole church to give Phoebe whatever she needed.', tea: 'Romans sixteen. Paul opens the final chapter of the most theologically dense letter in the New Testament with a personal commendation. I commend unto you Phebe our sister, which is a servant of the church which is at Cenchrea. The word behind servant there is diakonos, which elsewhere gets translated deacon or minister, and translators have gone back and forth on it for centuries. Then he asks the Roman church to receive her in the Lord, as becometh saints, and to assist her in whatsoever business she hath need of you. Give her whatever she needs. And then his reason. For she hath been a succourer of many, and of myself also. A patron. A protector. She had backed Paul personally. Now, you will often hear that Phoebe carried the letter to Rome. That is not stated in the text. It is a very old and very reasonable inference from the fact that she is commended first, at the front of the greetings, in the way a letter carrier would be. Reasonable inference, not chapter and verse.', ref: 'Romans 16:1', book: 'Romans', chapter: 16, mood: 'dark', order: 29 },
  { id: 'mary-perfume', durationSeconds: 56, heat: 3, badge: 'Wild', hook: 'She poured out a fortune on his feet and let them talk.', tea: 'John twelve. Six days before the Passover, in Bethany, at a supper where Martha is serving and Lazarus is at the table. Mary takes a pound of ointment of spikenard, very costly, and anoints the feet of Jesus, and wipes his feet with her hair. And the house was filled with the odour of the ointment. Then Judas Iscariot objects, and he uses the language of compassion. Why was not this ointment sold for three hundred pence, and given to the poor? Three hundred pence is roughly a year of a labourer\'s wages, going by a day\'s wage being a penny elsewhere in the Gospels. So the criticism is not absurd on its face. Except John tells us the motive outright. He said this, not that he cared for the poor, but because he was a thief, and had the bag, and bare what was put therein. And Jesus says, let her alone. Against the day of my burying hath she kept this. He defends her in the room, out loud, in front of the man doing the accounting.', ref: 'John 12:7', book: 'John', chapter: 12, mood: 'light', order: 30 },
];

/** Normalize so every entry has media + duration without repeating it 30 times. */
export const TEAS: Tea[] = SEED.map((t) => ({
  ...t,
  likes: t.likes ?? 0,
  image: t.image ?? `/img/tea/${t.id}.jpg`,
  audioUrl: t.audioUrl ?? TEA_AUDIO_URL,
  durationSeconds: t.durationSeconds ?? 62,
}));

export function getTea(id: string) {
  return TEAS.find((t) => t.id === id) ?? null;
}

/**
 * Stable per calendar day, with no repeat inside a 30-day cycle. Uses whole days
 * since the epoch, so every client that agrees on the date agrees on the tea.
 */
export function teaOfDay(d: Date = new Date()): Tea {
  const day = Math.floor(d.getTime() / 86_400_000);
  const ordered = [...TEAS].sort((a, b) => a.order - b.order);
  return ordered[((day % ordered.length) + ordered.length) % ordered.length];
}

export function resolveTeaAudioUrl(tea: Tea): string | null {
  const url = tea.audioUrl ?? TEA_AUDIO_URL;
  return url.replace('{teaId}', tea.id);
}

export function teaForClient(tea: Tea) {
  const audioUrl = resolveTeaAudioUrl(tea);
  return { ...tea, hasAudio: Boolean(audioUrl), audioUrl };
}
