// Tea — a daily sermon. One ~60 second clip a day, with a scrollable archive of
// 30 to start. Sassy, modern, reverent. Copy is deliberately bold but never
// mocks Scripture; product/theology review before ship.
//
// House style: no em-dashes anywhere in this file's user-facing copy. Use a
// comma, a period, or "and".
export type Tea = {
  id: string;
  /**
   * The card's preview title: 3 to 4 words, sharp and specific to the passage.
   *
   * Deliberately its own field rather than a slice of `hook` or `tea`. A card
   * used to show the opening words of the narration, so the grid read as a wall
   * of truncated paragraphs with no way to tell one card from another at a
   * glance. This is the line that has to work as a thumbnail; `hook` remains the
   * full shareable sentence on the detail screen.
   *
   * Rules: drawn from what actually happens in the passage, often the KJV's own
   * words. Never generic clickbait, never the first words of the narration.
   */
  cardTitle: string;
  hook: string; // the shareable serif line
  tea: string; // 2 to 3 punchy sentences, ~60s narrated
  badge: string; // "Today's tea" | 'Plot twist' | 'Hot take' | 'Receipts' | 'Wild'
  ref: string;
  book: string;
  chapter: number;
  mood: 'dark' | 'light';
  /** 1 warm, 2 spicy, 3 wild. Drives the badge + card treatment. */
  heat: 1 | 2 | 3;
  likes: number;
  order: number;
  /**
   * Per-Tea art. `/img/tea/<id>.jpg` by default, served by the static image
   * route; set an absolute URL to point at a CDN without touching any screen.
   * Null means "no art commissioned yet" and the client draws its deterministic
   * fallback, so the layout never depends on the file existing.
   */
  image?: string | null;
  /**
   * Where the subject sits in the frame. Tea Detail is a vertical recording
   * surface with text along the bottom, so art is cropped to this anchor rather
   * than centre-cropped, keeping faces/objects clear of the caption block.
   */
  focal?: 'top' | 'center' | 'bottom';
  /** Optional per-image scrim override when a still is unusually light or busy. */
  scrim?: string | null;
  /** Credit line, shown small on Tea Detail when art is licensed. */
  credit?: string | null;
  audioUrl?: string | null; // '/audio/tea-<id>.mp3' (~60s)
  durationSeconds?: number; // 55 to 70
  voice?: string | null; // optional per-card ElevenLabs voice override
};

/** Default template: pre-rendered static MP3 per tea, served by /audio/:filename. */
const TEA_AUDIO_URL = '/audio/tea-{teaId}.mp3';

type TeaSeed = Omit<Tea, 'likes' | 'image' | 'audioUrl' | 'durationSeconds' | 'focal' | 'scrim' | 'credit'> & {
  likes?: number;
  image?: string | null;
  audioUrl?: string | null;
  durationSeconds?: number;
  focal?: 'top' | 'center' | 'bottom';
  scrim?: string | null;
  credit?: string | null;
};

const SEED: TeaSeed[] = [
  { id: 'vashti-no', cardTitle: 'She Would Not Come', durationSeconds: 74, heat: 2, badge: "Today's tea", hook: 'Honey, gather \'round. It\'s Grace, and I am about to spill the tea straight from Esther chapter 1. No fanfic. No "maybe she was pregnant." No "maybe the crown was heavy." Just the text, served icy.', tea: 'So there\'s this king. One hundred and twenty-seven provinces. Seven-day banger, royal wine, whole city invited. Day seven, direct quote: "the king\'s heart was merry with wine." Cute. He sends seven yes-men to fetch his wife. "Bring Queen Vashti out in the royal crown. Let the people and the princes look at her beauty." Meanwhile? Vashti is throwing her own feast for the women that same week. Same palace. She says no. That\'s the entire receipt. Scripture records the refusal and not one syllable about why. Anybody inventing her reasons is writing fanfiction. Does he go talk to his wife? Absolutely not. He convenes a panel and asks, "According to the law, what do we do with Queen Vashti?" Enter Memucan. He stands up and says, and I am not exaggerating, "This isn\'t just about you, king. If word gets out, every woman in the empire hears it, and they will start despising their husbands." So they write it into the unchangeable law of the Persians and Medes. Vashti never comes before the king again. Letters fly out in every language: every man shall rule his own house. One woman said no. And an entire empire passed legislation about it. No notes.', ref: 'Esther 1:12', book: 'Esther', chapter: 1, mood: 'dark', order: 1 },
  { id: 'ruth-field', cardTitle: 'Loyalty In The Barley', durationSeconds: 69, heat: 1, badge: 'Plot twist', hook: 'Widowed, broke, foreign, and she still says the most loyal sentence in the Bible.', tea: 'Naomi loses her husband. Then both her sons. She is left with two daughters in law in a country that isn\'t hers, and she tells them both to go home. Twice. She\'s not being cold, she\'s being honest. She\'s got nothing to give them. Orpah kisses her and goes. Nobody should drag Orpah, she did exactly what she was told. But Ruth clave unto her. And she says, "Whither thou goest, I will go. Thy people shall be my people, and thy God my God." That\'s a vow with a curse attached. She means it. So they walk into Bethlehem with nothing, right as barley harvest starts. And Ruth goes to work, gleaning the leftovers, because the law said the poor get to follow the reapers. And the text says her hap was to light on a field belonging to Boaz. Her happenstance. Sure. The book spends two more chapters showing you what that was. Boaz clocks her immediately. Tells his men not to touch her. Tells her to drink their water. Then quietly tells them to drop extra grain where she\'ll find it. She goes home with about an ephah of barley. That is a wildly good day. Chapters later, Boaz redeems the family at the town gate, and Ruth has a son named Obed. Obed\'s son is Jesse. Jesse\'s son is David. Loyalty is a flex.', ref: 'Ruth 2:2', book: 'Ruth', chapter: 2, mood: 'light', order: 2 },
  { id: 'deborah-palm', cardTitle: 'Court Under A Palm', durationSeconds: 59, heat: 2, badge: 'Receipts', hook: 'A woman is running an entire nation from under a tree and the general will not go to war without her.', tea: 'Judges chapter four. Deborah. Prophetess. And the text says plainly, she judged Israel at that time. Not helped. Judged. She holds court under a palm tree between Ramah and Bethel, and the children of Israel come up to her for judgment. That is the office. Written down. No hedging. So she summons Barak, the military commander, and gives him God\'s orders. Take ten thousand men to mount Tabor. And Barak, a grown general, says, "If thou wilt go with me, then I will go. But if thou wilt not go with me, then I will not go." Sir. She goes. Of course she goes. But she calls it first: "The journey that thou takest shall not be for thine honour, for the Lord shall sell Sisera into the hand of a woman." She told him exactly how it would end. And that is exactly how it ended, in a tent, with another woman named Jael. Deborah didn\'t just judge. She called the shot, went anyway, and let the record show who did the work. Palm tree. Whole nation. No notes.', ref: 'Judges 4:4', book: 'Judges', chapter: 4, mood: 'dark', order: 3 },
  { id: 'abigail-intercept', cardTitle: 'She Intercepted A King', durationSeconds: 70, heat: 2, badge: 'Hot take', hook: 'Okay this one has a man so awful that Scripture literally says his name means fool.', tea: 'Nabal. Three thousand sheep, a thousand goats, shearing season, rolling in it. And David, before he\'s king, has been out in the wilderness guarding this man\'s shepherds. For free. The servants say it themselves: they were a wall unto us, night and day. So David sends ten men to ask, politely, for provisions. And Nabal goes, "Who is David? Who is the son of Jesse?" Then, "Shall I take my bread and my water and my meat, and give it to men I know not whence they be?" Sir. You know exactly who he is. David\'s reply is two words. "Gird ye on every man his sword." Four hundred men. He is riding out to erase an entire household over a dinner request. Now. A servant runs to Nabal\'s wife, because the staff know you cannot talk to this man. Enter Abigail. And she does not panic, she does inventory. Two hundred loaves. Two skins of wine. Five dressed sheep. Roasted grain. A hundred raisin cakes. Two hundred fig cakes. Loaded on donkeys, sent ahead. And she tells her husband nothing. She rides straight at four hundred armed men, gets off the donkey, falls on her face, and takes the blame herself. Then she tells David: do not let this blood be on you, because God is going to build you a sure house, and you do not want this on the record. And David says, "Blessed be thy advice, and blessed be thou, which hast kept me this day from coming to shed blood." She talked a future king out of a massacre. With groceries and a speech.', ref: '1 Samuel 25:18', book: '1 Samuel', chapter: 25, mood: 'light', order: 4 },
  { id: 'mary-yes', cardTitle: 'The Most Costly Yes', durationSeconds: 63, heat: 1, badge: "Today's tea", hook: 'An angel shows up in a nowhere town and hands a young woman the most terrifying yes in history.', tea: 'Gabriel gets sent to Nazareth. Not Jerusalem. Not the temple. A village. To a virgin promised to a man named Joseph. And her name is Mary. Quick note, because everybody gets this wrong. Luke gives us the town, the fiancé, his royal line. He never gives us her age. So when you hear teenager, that\'s tradition talking, not the text. The angel opens with, "Hail, thou that art highly favoured, the Lord is with thee." And she\'s troubled. Not by the angel. By the greeting. She\'s turning the words over trying to work out what kind of hello that is. Then the news lands. You\'ll conceive, you\'ll have a son, call him Jesus, and his kingdom will have no end. Now sit in that. She\'s engaged. Not married. In her village, in her century, this news is not a blessing, it\'s a scandal that could cost her everything. And her one question is not can God do this. It\'s, "How shall this be, seeing I know not a man?" She\'s not asking for proof. She\'s asking how. And when he answers, she says, "Behold the handmaid of the Lord. Be it unto me according to thy word." Yes to a plan she cannot verify. In a town that could count.', ref: 'Luke 1:38', book: 'Luke', chapter: 1, mood: 'dark', order: 5 },
  { id: 'martha-mary', cardTitle: 'The Better Part', durationSeconds: 61, heat: 1, badge: 'Plot twist', hook: 'Two sisters, one house, and one of them is about to get publicly told, and it is not who you think.', tea: 'Jesus comes into a village. Martha receives him into her house. Her house. She\'s the host, this was her call. Her sister Mary sits down at his feet and just, listens. And Martha is what the text calls cumbered about much serving. Cumbered. Dragged in every direction. Because hosting is real work, and she is doing all of it, alone, while her sister sits on the floor. So Martha does what a lot of us do. She doesn\'t go to Mary. She goes over her head. "Lord, dost thou not care that my sister hath left me to serve alone? Bid her therefore that she help me." She\'s not asking. She\'s telling him to sort out her sister. And here\'s where everybody expects a scolding. He says, "Martha, Martha." Her name. Twice. That is not how you open a telling-off. That is how you talk to somebody you love who is drowning. "Thou art careful and troubled about many things. But one thing is needful, and Mary hath chosen that good part, which shall not be taken away from her." Read what he did not say. He never tells Mary to get up. He never says the serving was wrong. He tells Martha she\'s allowed to sit down too.', ref: 'Luke 10:42', book: 'Luke', chapter: 10, mood: 'light', order: 6 },
  { id: 'well-woman', cardTitle: 'She Left The Waterpot', durationSeconds: 57, heat: 3, badge: 'Wild', hook: 'She came for water at the worst hour of the day and left as the first person to go preach him.', tea: 'John four. Jesus is tired, sits down by a well, and it\'s about the sixth hour. Midday. And a woman of Samaria comes to draw water. He says, "Give me to drink." Scandal. Two of them. She says it herself: "How is it that thou, being a Jew, askest drink of me, which am a woman of Samaria?" Then the conversation turns. He offers her living water. She wants it. He says go call your husband. And she says, "I have no husband." And he goes, "Thou hast well said. For thou hast had five husbands, and he whom thou now hast is not thy husband." He\'s not dragging her. He\'s telling her he already knows and he\'s still sitting there. Now, people love to say she came at noon to dodge the gossip. That is a reasonable guess. It is still a guess. The text just says sixth hour. What the text does say is this. She left her waterpot. Left it. And went into the city and told the men, "Come, see a man which told me all things that ever I did." She dropped the jar and became the testimony.', ref: 'John 4:28', book: 'John', chapter: 4, mood: 'dark', order: 7 },
  { id: 'esther-uninvited', cardTitle: 'If I Perish', durationSeconds: 63, heat: 2, badge: 'Hot take', hook: 'Walking into that throne room uninvited was a death sentence, and she put on the crown and did it anyway.', tea: 'One law in Persia. Man or woman, you come to the king unsummoned, you die. Unless he holds out the golden sceptre. And Esther tells Mordecai the part that had to keep her up at night: "I have not been called to come in unto the king these thirty days." Thirty days. She\'s the queen. She has no idea where she stands. And Mordecai\'s reply is brutal and kind at the same time. "Think not with thyself that thou shalt escape in the king\'s house, more than all the Jews." You are not safe. The palace is not a shelter. Then: if you stay silent, deliverance will arise from another place, but you and your father\'s house will be destroyed. Hear that theology. He never says God will fail. He says rescue is coming and you might miss it. "And who knoweth whether thou art come to the kingdom for such a time as this?" A question. Not a command. He leaves her free. So she fasts three days and sends back, "If I perish, I perish." Third day, royal apparel, inner court. And the king holds out the sceptre. She lives. And then she throws the dinner party that flips an empire.', ref: 'Esther 4:16', book: 'Esther', chapter: 4, mood: 'light', order: 8 },
  { id: 'hannah-prayer', cardTitle: 'Only Her Lips Moved', durationSeconds: 67, heat: 1, badge: "Today's tea", hook: 'She prayed so hard the priest thought she was drunk and told her to sober up.', tea: 'Elkanah has two wives. Peninnah has kids. Hannah doesn\'t. And Scripture calls Peninnah her adversary, and says she provoked her sore, year after year, every single time they went up to worship. At the one place she goes to meet God. So Hannah stops eating and weeps. And her husband, who genuinely loves her, says the most well-meaning wrong thing in the Bible: "Am not I better to thee than ten sons?" Sir. Read the room. So she gets up from the table and goes to the house of the Lord. And she prays in bitterness of soul. Here\'s the detail. She spake in her heart. Only her lips moved. Her voice was not heard. And Eli the priest, whose actual job is recognising devotion, watches her mouth and decides she\'s drunk. Out loud. "How long wilt thou be drunken? Put away thy wine from thee." And Hannah does not shrink and does not fight. She says, "No, my lord. I am a woman of a sorrowful spirit. I have poured out my soul before the Lord." The most honest prayer in that building. And the priest called her a drunk. She walks out still childless. And the text says her countenance was no more sad.', ref: '1 Samuel 1:13', book: '1 Samuel', chapter: 1, mood: 'dark', order: 9 },
  { id: 'magdalene-first', cardTitle: 'The First To See', durationSeconds: 53, heat: 2, badge: 'Receipts', hook: 'Everybody went home. She stayed and cried in a graveyard. So she\'s the one who saw him first.', tea: 'John twenty. Mary Magdalene comes to the tomb while it\'s still dark, sees the stone gone, and runs for Peter and John. They sprint back, look in, see the linen, and then the text says it plainly. They went away again unto their own home. They left. She didn\'t. Mary stood without at the sepulchre weeping. So she\'s the one there when two angels ask why she\'s crying. And she says, "Because they have taken away my Lord, and I know not where they have laid him." Then she turns around, sees a man, and thinks he\'s the gardener. Says, "Sir, if thou have borne him hence, tell me where thou hast laid him, and I will take him away." She\'s devastated and still trying to handle the logistics herself. And he says one word. "Mary." That\'s it. That\'s the whole thing. He says her name and she knows. Then he sends her. Go to my brethren and tell them. And Mary Magdalene came and told the disciples that she had seen the Lord. The resurrection gets announced by a woman who wouldn\'t leave.', ref: 'John 20:18', book: 'John', chapter: 20, mood: 'light', order: 10 },
  { id: 'rahab-rope', cardTitle: 'The Scarlet Cord', durationSeconds: 60, heat: 3, badge: 'Wild', hook: 'She ran a house on the city wall, lied to the king\'s face, and negotiated her whole family out of a war.', tea: 'Joshua two. Two Israelite spies come into Jericho and stay at the house of a woman named Rahab. The text says what she is. It doesn\'t soften it and neither will I. The king finds out and sends men to bring them out. And Rahab hides the spies, then tells the king\'s messengers, "There came men unto me, but I wist not whence they were." Then sends them chasing in the wrong direction. She lied to a king. The Bible records it. Then she goes up to the roof and tells the spies the actual reason. "I know that the Lord hath given you the land." She\'d heard what happened at the Red Sea. She says, "Our hearts did melt." And then, "The Lord your God, he is God in heaven above, and in earth beneath." That\'s a confession of faith from a Canaanite sex worker, and it\'s more theologically sharp than most of Israel manages that decade. Then she negotiates. And notice, not for herself. "Save alive my father, and my mother, and my brethren, and my sisters, and all that they have." Scarlet cord in the window. Her whole household lives. And Matthew puts her in the family line of Jesus.', ref: 'Joshua 2:4', book: 'Joshua', chapter: 2, mood: 'dark', order: 11 },
  { id: 'jael-tent', cardTitle: 'Milk, Then A Hammer', durationSeconds: 63, heat: 3, badge: 'Wild', hook: 'Fair warning. This one is violent, and I am not softening it, because Scripture doesn\'t.', tea: 'Sisera. Commander of nine hundred iron chariots. Twenty years of crushing Israel. And he has just watched his entire army fall apart, so he\'s running. On foot. Alone. He heads for the tent of a woman named Jael, because there\'s peace between his king and her husband\'s house. He thinks he\'s found neutral ground. Jael comes out to meet him. And she says, "Turn in, my lord, turn in to me. Fear not." Fear not. Remember that. He goes in. She covers him with a blanket. He says, "Give me a little water to drink, for I am thirsty." She opens a skin of milk instead, gives him a drink, and covers him again. Then he gives her instructions. Stand in the door. If anybody asks whether there\'s a man in here, say no. And the text says he was fast asleep, and weary. So Jael takes a tent peg and a hammer, and goes softly, and it is over. Then she walks out, finds Barak, and says, "Come, and I will shew thee the man whom thou seekest." The audacity of that sentence. And here\'s the part people skip. Deborah puts it in a song. "Blessed above women shall Jael be." He asked for water. She gave him milk. Scripture does not flinch. And neither will I.', ref: 'Judges 4:21', book: 'Judges', chapter: 4, mood: 'dark', order: 12 },
  { id: 'tamar-veil', cardTitle: 'She Took His Signet', durationSeconds: 65, heat: 3, badge: 'Wild', hook: 'This chapter is rough, and it ends with a patriarch admitting a woman he tried to burn was more righteous than him.', tea: 'Genesis thirty-eight. Tamar marries Judah\'s oldest son. He dies. By custom she\'s given to the next brother. He dies too. Judah\'s got a third son, Shelah, and he tells Tamar go live as a widow at your father\'s house until he grows up. And then he never sends for her. She is parked. No husband, no children, no standing, and no legal way to fight it. Years pass. She sees Shelah is grown and she has been left there. So she takes off her widow\'s clothes, covers herself with a veil, and sits by the road to Timnath. Judah goes past, doesn\'t recognise her, and propositions her. And here\'s where she gets sharp. He offers a young goat. She says, "Wilt thou give me a pledge, till thou send it?" He says what pledge. And she names three things. His signet, his bracelets, his staff. That is his ID. She took his ID. Three months later, word gets to Judah that she\'s pregnant. And he says, "Bring her forth, and let her be burnt." And she sends him his own signet and staff with a message. "Discern, I pray thee, whose are these." And Judah says it out loud. "She hath been more righteous than I."', ref: 'Genesis 38:26', book: 'Genesis', chapter: 38, mood: 'light', order: 13 },
  { id: 'miriam-song', cardTitle: 'Timbrel On The Shore', durationSeconds: 55, heat: 1, badge: 'Plot twist', hook: 'She watched the water close, picked up a tambourine, and started the party on the far shore.', tea: 'Exodus fifteen. Israel has just walked through the sea on dry ground and watched it come down behind them. Now, order matters here, so let\'s be accurate. Moses and the children of Israel sing first. That\'s verse one. Then verse twenty. "And Miriam the prophetess, the sister of Aaron, took a timbrel in her hand. And all the women went out after her with timbrels and with dances." And Miriam answered them. Answered. She takes the song and she leads the women in it, with percussion and dancing, standing on the edge of an impossible crossing. "Sing ye to the Lord, for he hath triumphed gloriously. The horse and his rider hath he thrown into the sea." Two things Scripture calls her right there in one verse. Prophetess. And sister of Aaron. Exodus two never names the sister who watched a baby float away in a basket. Numbers twenty-six names Miriam among those siblings, and that\'s the connection most readers make. What isn\'t in doubt is this. When the water closed, she was the one who picked up an instrument.', ref: 'Exodus 15:20', book: 'Exodus', chapter: 15, mood: 'light', order: 14 },
  { id: 'shunammite', cardTitle: 'I Will Not Leave', durationSeconds: 67, heat: 2, badge: 'Receipts', hook: 'Her son died on her lap and she got on a donkey and went to argue with a prophet.', tea: 'Second Kings four. This woman is described as great. Standing, money, influence. She\'s the one who notices Elisha passing through and builds him a room. Bed, table, stool, candlestick. He wants to repay her. She says no. She\'s fine. He gives her a son anyway. Years later the boy\'s out in the field, says "My head, my head," and is carried to his mother. And the text says he sat on her knees till noon, and then died. Now watch her. She carries him upstairs, lays him on the prophet\'s bed, shuts the door, and calls for a donkey. Her husband asks why she\'s going, it isn\'t new moon or sabbath. She says, "It shall be well." She does not tell him the child is dead. She\'s not asking permission, she\'s going. She rides to Carmel. Elisha\'s servant tries to intercept her with polite questions. She blows straight past him. Then she catches Elisha by the feet. And Gehazi moves to shove her off, and Elisha says, "Let her alone, for her soul is vexed within her." And she says, "As the Lord liveth, and as thy soul liveth, I will not leave thee." He got up and followed her. Faith can look like refusing to be managed.', ref: '2 Kings 4:30', book: '2 Kings', chapter: 4, mood: 'dark', order: 15 },
  { id: 'widow-oil', cardTitle: 'Borrow Not A Few', durationSeconds: 55, heat: 1, badge: "Today's tea", hook: 'The creditors were coming for her sons and all she had was one jar of oil.', tea: 'Second Kings four, opening scene. A widow cries out to Elisha and lays out the situation. Her husband is dead. He feared the Lord. And the creditor is coming to take her two sons to be his slaves. Not the furniture. The children. That\'s the debt system she\'s trapped in. And Elisha asks a question I think about a lot. "What shall I do for thee? Tell me, what hast thou in the house?" And she says, "Thine handmaid hath not any thing in the house, save a pot of oil." Nothing. Except one thing. And he says go borrow vessels from all your neighbours. Empty ones. And then, and this is the line, "Borrow not a few." So she does. Shuts the door on herself and her sons, and starts pouring. And it keeps coming. Vessel after vessel. Until she says to her son, "Bring me yet a vessel." And he says, "There is not a vessel more." And the oil stayed. Read that again. The supply stopped exactly when the containers did. She sells it, pays the debt, and lives on the rest.', ref: '2 Kings 4:6', book: '2 Kings', chapter: 4, mood: 'light', order: 16 },
  { id: 'bleeding-woman', cardTitle: 'Twelve Years, One Touch', durationSeconds: 56, heat: 2, badge: 'Hot take', hook: 'Twelve years of bleeding, every doctor paid, and Mark says she was nothing bettered, but rather grew worse.', tea: 'That\'s the text. Not my summary. Mark writes that she suffered many things of many physicians and spent all that she had, and got worse. Twelve years. Broke. Out of options. So she hears about Jesus, and she does not go to the front and ask. She comes up behind him in a crowd, because she says within herself, "If I may touch but his clothes, I shall be whole." And she does. And immediately it stops. She could have walked. That was the plan. Get in, get out, nobody knows. And he stops the entire procession. In a crowd pressing on him from every side he turns around and says, "Who touched my clothes?" And the disciples basically tell him that\'s an insane question. Look at this crowd. He keeps looking. So she comes fearing and trembling, falls down, and tells him all the truth. Not a summary. All of it. And he says, "Daughter, thy faith hath made thee whole. Go in peace." Daughter. In front of everybody. He wouldn\'t let her leave as a secret.', ref: 'Mark 5:34', book: 'Mark', chapter: 5, mood: 'dark', order: 17 },
  { id: 'canaanite-mother', cardTitle: 'She Argued For Crumbs', durationSeconds: 62, heat: 3, badge: 'Wild', hook: 'A foreign mother argues theology with Jesus in public and he tells her she won.', tea: 'Matthew fifteen. Jesus goes into the coasts of Tyre and Sidon, and a woman of Canaan comes out after him, crying, "Have mercy on me, O Lord, thou Son of David. My daughter is grievously vexed with a devil." And the text says something that stops you cold. "But he answered her not a word." Silence. Then the disciples get involved, and not helpfully. "Send her away, for she crieth after us." They\'re not moved, they\'re annoyed. Then he says he was sent to the lost sheep of the house of Israel. She doesn\'t leave. She comes and worships him and says three words. "Lord, help me." And then he gives her the hard line. "It is not meet to take the children\'s bread, and to cast it to dogs." Now people argue endlessly about his tone there. The text does not give us tone, so hold your theory loosely. What isn\'t in dispute is her comeback. "Truth, Lord. Yet the dogs eat of the crumbs which fall from their masters\' table." She takes his own metaphor, accepts the terms, and turns it. And he says, "O woman, great is thy faith. Be it unto thee even as thou wilt." Healed that hour.', ref: 'Matthew 15:28', book: 'Matthew', chapter: 15, mood: 'light', order: 18 },
  { id: 'anna-temple', cardTitle: 'Decades Of Showing Up', durationSeconds: 51, heat: 1, badge: 'Plot twist', hook: 'She waited decades in the temple and recognised him the second he walked through the door.', tea: 'Luke two. Anna. Prophetess. Daughter of Phanuel, tribe of Aser. Luke says she was of a great age, married seven years, and then a widow of about fourscore and four years. Quick honesty note. Translators split on that. It either means she was eighty-four, or she\'d been widowed for eighty-four years. Both readings are a very long wait, and anybody who picks the one that preaches better is doing you dirty. What is not ambiguous is how she spent it. She departed not from the temple, but served God with fastings and prayers night and day. Night and day. For decades. In a building, waiting. And then one ordinary morning a poor couple carries a newborn in to do what the law required. Nothing about it looks special. And Anna comes in that instant. She gives thanks to God, and she spake of him to all them that looked for redemption in Jerusalem. Decades of showing up. And she knew him immediately, and she started telling everybody who would listen. Patience is not passivity.', ref: 'Luke 2:38', book: 'Luke', chapter: 2, mood: 'dark', order: 19 },
  { id: 'lydia-house', cardTitle: 'And She Constrained Us', durationSeconds: 55, heat: 2, badge: 'Receipts', hook: 'She heard one sermon by a river and then strong-armed the apostles into moving in.', tea: 'Acts sixteen. Paul and his companions get to Philippi, and on the sabbath they go out of the city by a river side, where prayer was made. They sit down and speak to the women who gathered there. And there\'s Lydia. Seller of purple, from Thyatira. Purple is the luxury trade. She has money and she runs a business. And the text says the Lord opened her heart, that she attended unto the things which were spoken of Paul. She\'s baptized. Her whole household with her. And then she makes an offer that is not really an offer. "If ye have judged me to be faithful to the Lord, come into my house, and abide there." And Luke adds four words that tell you everything. "And she constrained us." She talked them into it. That is the phrasing. She would not take no. And here\'s the receipt. Later in that same chapter, after Paul and Silas get out of prison, where do they go? They entered into the house of Lydia. Her house was the base of operations. Not asked. Told.', ref: 'Acts 16:15', book: 'Acts', chapter: 16, mood: 'light', order: 20 },
  { id: 'priscilla-teach', cardTitle: 'She Taught The Teacher', durationSeconds: 58, heat: 2, badge: 'Hot take', hook: 'A woman took the most famous preacher in the city aside and corrected his theology.', tea: 'Acts eighteen. A man named Apollos shows up in Ephesus. Born in Alexandria. The text calls him eloquent, and mighty in the scriptures. He teaches diligently the things of the Lord. He\'s genuinely gifted. And then one clause changes everything. "Knowing only the baptism of John." He\'s brilliant, and he\'s behind. He\'s got maybe eighty percent of it, preaching with total confidence. So he starts speaking boldly in the synagogue, and Aquila and Priscilla hear him. And here is the move. They do not stand up in the middle of the synagogue and correct him publicly. They do not subtweet him. "Whom when Aquila and Priscilla had heard, they took him unto them, and expounded unto him the way of God more perfectly." Took him aside. Filled in what was missing. Protected his ministry while they fixed it. And Apollos goes on to help the believers enormously and convince people publicly. Small thing readers have made a lot of. In several places her name is listed first, including this one. Luke never tells us why, so treat the theories as theories. What we can see is that she taught the teacher.', ref: 'Acts 18:26', book: 'Acts', chapter: 18, mood: 'dark', order: 21 },
  { id: 'sarah-laugh', cardTitle: 'Laughter Behind The Tent', durationSeconds: 63, heat: 2, badge: 'Plot twist', hook: 'She laughed at God from behind a tent flap, lied about it, got caught, and still got the promise.', tea: 'Genesis eighteen. Three visitors come to Abraham\'s tent in the heat of the day. Big hospitality scramble. And one of them says, "Lo, Sarah thy wife shall have a son." And Sarah is listening at the tent door behind him. The text is blunt about the situation. They are old. Well stricken in age. It says plainly that it had ceased to be with Sarah after the manner of women. So she laughed within herself. Not out loud. Inside. And said, "After I am waxed old shall I have pleasure, my lord being old also?" And then the Lord says to Abraham, "Wherefore did Sarah laugh?" Caught. Instantly. Laughing silently, inside her own head, behind a tent flap. And then, "Is any thing too hard for the Lord?" And Sarah, understandably, panics. "I laughed not." Because she was afraid. And he says, gently and immovably, "Nay, but thou didst laugh." He does not withdraw the promise. He does not scold her out of the story. Genesis twenty-one, she has the boy. Names him Isaac, which means laughter. And says, "God hath made me to laugh."', ref: 'Genesis 18:12', book: 'Genesis', chapter: 18, mood: 'light', order: 22 },
  { id: 'hagar-seen', cardTitle: 'Thou God Seest Me', durationSeconds: 70, heat: 2, badge: "Today's tea", hook: 'A pregnant slave girl runs into a desert to die, and God shows up and lets her name him.', tea: 'Let\'s set it. Sarai can\'t have children. So she gives her Egyptian handmaid Hagar to Abram, to get a child through her. Nobody asks Hagar anything. She is a solution to somebody else\'s problem. She conceives. Tension explodes. Sarai says to Abram, "My wrong be upon thee." And Abram, husband of the year, goes, "Behold, thy maid is in thy hand. Do to her as it pleaseth thee." He hands her back. And the text says Sarai dealt hardly with her. So Hagar runs. Pregnant. Alone. Into wilderness. With no plan, because there isn\'t one. And the angel of the Lord finds her by a spring of water. Not in a temple. Not in a camp. By a spring, in the middle of nowhere. And he says, "Hagar, Sarai\'s maid, whence camest thou? And whither wilt thou go?" Where did you come from. Where are you going. She answers the first one. "I flee from the face of my mistress Sarai." She does not answer the second, because she has nowhere to go and they both know it. Then he tells her she\'ll bear a son, and to call him Ishmael, because the Lord hath heard thy affliction. And then Hagar does something nobody in Scripture has done yet. She names God. "Thou God seest me." A runaway. A foreigner. A slave. And she is the one who gets to say it.', ref: 'Genesis 16:13', book: 'Genesis', chapter: 16, mood: 'dark', order: 23 },
  { id: 'zelophehad', cardTitle: 'Five Sisters Speak Right', durationSeconds: 57, heat: 3, badge: 'Wild', hook: 'Five sisters walked up to Moses, the priest, the princes and the entire assembly, and changed inheritance law.', tea: 'Numbers twenty-seven. Their names are Mahlah, Noah, Hoglah, Milcah and Tirzah, and Scripture lists every single one. Their father died in the wilderness with no sons. Under the rules as they stood, land moved through sons. So his name and his portion just vanish. And these five women do not petition quietly. They stood before Moses, and before Eleazar the priest, and before the princes and all the congregation, at the door of the tabernacle. That is the entire leadership of the nation, plus everybody else. And five sisters walk up and make a legal argument. "Why should the name of our father be done away from among his family, because he hath no son? Give unto us therefore a possession among the brethren of our father." And Moses does not rule on it. He doesn\'t wing it. "And Moses brought their cause before the Lord." And the answer comes back. "The daughters of Zelophehad speak right." Speak right. God agreed with them, on the record, and the inheritance law of Israel was rewritten because five women asked.', ref: 'Numbers 27:7', book: 'Numbers', chapter: 27, mood: 'light', order: 24 },
  { id: 'huldah-scroll', cardTitle: 'They Asked The Prophetess', durationSeconds: 58, heat: 2, badge: 'Receipts', hook: 'They found a lost scroll, the king panicked, and the men on the payroll went and asked a woman what it meant.', tea: 'Second Kings twenty-two. They\'re renovating the temple, and Hilkiah the high priest finds the book of the law. Finds it. In the temple. That is its own scandal. Shaphan the scribe reads it to King Josiah. And the king rends his clothes, because he can hear how far the nation has drifted. So he needs a ruling. And he says, "Go ye, enquire of the Lord for me, and for the people, and for all Judah, concerning the words of this book." Now think about who is standing in that room. A high priest. A scribe. A whole religious establishment on salary. And they go to Huldah the prophetess. Five men, sent by a king, to a woman, for the authoritative reading of Scripture. And she does not soften it. She opens with, "Thus saith the Lord God of Israel." Judgment on the nation. And then mercy for Josiah personally, because, she says, thine heart was tender. Her reading became national policy. The whole reformation that follows runs on what she said.', ref: '2 Kings 22:14', book: '2 Kings', chapter: 22, mood: 'dark', order: 25 },
  { id: 'widow-mite', cardTitle: 'All Her Living', durationSeconds: 58, heat: 1, badge: 'Plot twist', hook: 'He sat down and watched people give, and the one he pointed at had less than everybody.', tea: 'Mark twelve. And the setup is the part people skip. "Jesus sat over against the treasury, and beheld how the people cast money into the treasury." He sat down. And watched. On purpose. And many that were rich cast in much. That\'s in the text too. It\'s not a lie, they gave a lot. Then a certain poor widow comes and throws in two mites. And Mark actually converts the currency for his readers, which tells you how small it was. Two mites, which make a farthing. And Jesus calls his disciples over. He wants them to see this specifically. "Verily I say unto you, that this poor widow hath cast more in, than all they which have cast into the treasury." More than all of them. Combined. And then he does the maths out loud. "For all they did cast in of their abundance. But she of her want did cast in all that she had, even all her living." All her living. Not a percentage. Everything. He is not measuring the gift. He is measuring what was left afterwards.', ref: 'Mark 12:44', book: 'Mark', chapter: 12, mood: 'light', order: 26 },
  { id: 'joanna-fund', cardTitle: 'Of Their Own Substance', durationSeconds: 52, heat: 2, badge: 'Hot take', hook: 'The most famous ministry in history was funded by women, and Luke names them on purpose.', tea: 'Luke chapter eight. Three verses that get skipped constantly. Jesus is going through every city and village preaching, and the twelve are with him. Standard. And then Luke adds, "And certain women, which had been healed of evil spirits and infirmities." And he names them. Mary called Magdalene, out of whom went seven devils. Joanna. Susanna. And many others. Stop on Joanna for a second, because Luke drops her job title like it\'s nothing. "Joanna the wife of Chuza Herod\'s steward." Herod\'s steward. That is a household manager inside the royal court. Which means Joanna had access, money, and an enormous amount to lose by being here. And then the line. "Which ministered unto him of their substance." Their substance. Their own resources. Luke did not have to write any of that down. He wanted somebody two thousand years later to know exactly who paid for it.', ref: 'Luke 8:3', book: 'Luke', chapter: 8, mood: 'dark', order: 27 },
  { id: 'dorcas-needle', cardTitle: 'The Coats She Made', durationSeconds: 57, heat: 1, badge: "Today's tea", hook: 'When she died, the widows didn\'t make speeches. They held up the clothes she made them.', tea: 'Acts nine. In Joppa there\'s a disciple named Tabitha, which translated is Dorcas. And the text says she was full of good works and almsdeeds which she did. Then she gets sick, and she dies. They wash her and lay her in an upper chamber. Lydda is near Joppa, and the disciples hear Peter is there, so they send two men and beg him to come without delay. Peter comes. They bring him upstairs. And here is the scene, and it wrecks me every time. "All the widows stood by him weeping, and shewing the coats and garments which Dorcas made, while she was with them." They are holding up the clothes. That\'s the eulogy. Not a speech. Evidence. And you have to understand what widows were in that world. Almost no safety net. And this woman had been quietly making them clothes with her own hands. Peter puts everybody out of the room, kneels down, prays, and turns to the body. "Tabitha, arise." And she opened her eyes. And sat up. And he called the saints and widows and presented her alive.', ref: 'Acts 9:39', book: 'Acts', chapter: 9, mood: 'light', order: 28 },
  { id: 'phoebe-letter', cardTitle: 'A Succourer Of Many', durationSeconds: 63, heat: 2, badge: 'Receipts', hook: 'Paul opens the most famous letter in the New Testament by telling an entire church to give this woman whatever she asks for.', tea: 'Romans sixteen. The final chapter. And Paul starts it with a personal commendation. "I commend unto you Phebe our sister, which is a servant of the church which is at Cenchrea." Now, that word servant. In Greek it\'s diakonos. Elsewhere in the New Testament translators render that same word deacon, or minister. Here, historically, a lot of them chose servant. Scholars have gone back and forth on it for centuries and you should know that\'s a translation decision, not a settled fact. Then Paul asks the Roman church to receive her, and, "that ye assist her in whatsoever business she hath need of you." Whatever she needs. Give it to her. And then his reason. "For she hath been a succourer of many, and of myself also." A patron. A protector. She had backed Paul personally. One more thing, and I want to be straight with you. You\'ll often hear that Phoebe carried the letter to Rome. That is a very old and very reasonable inference, because she\'s commended first, right at the front. It is not stated in the text. Inference, not chapter and verse.', ref: 'Romans 16:1', book: 'Romans', chapter: 16, mood: 'dark', order: 29 },
  { id: 'mary-perfume', cardTitle: 'A Year Poured Out', durationSeconds: 57, heat: 3, badge: 'Wild', hook: 'She poured a year\'s wages onto his feet in a room full of people doing the math out loud.', tea: 'John twelve. Six days before Passover, in Bethany. Supper. Martha\'s serving, Lazarus is at the table. And Mary takes a pound of ointment of spikenard, very costly, and anoints the feet of Jesus, and wipes his feet with her hair. And the house was filled with the odour of the ointment. Everybody in that room knows exactly what just happened, because they can smell it. Then Judas speaks up. And he uses the language of compassion. "Why was not this ointment sold for three hundred pence, and given to the poor?" Three hundred pence. Going by a penny being a day\'s wage elsewhere in the Gospels, that\'s roughly a year of work. Poured out on the floor. So on the face of it, it\'s not a stupid question. Except John tells us the motive outright. "This he said, not that he cared for the poor, but because he was a thief, and had the bag." He was skimming. And Jesus does not let her sit there and take it. "Let her alone. Against the day of my burying hath she kept this." He defended her out loud, in the room, in front of the man counting.', ref: 'John 12:7', book: 'John', chapter: 12, mood: 'light', order: 30 },
];

/** Normalize so every entry has media + duration without repeating it 30 times. */
export const TEAS: Tea[] = SEED.map((t) => ({
  ...t,
  likes: t.likes ?? 0,
  // Art is addressed per Tea from day one. Dropping 30 stills into
  // public/img/tea/ (or setting an absolute CDN url per entry) lights them up
  // with no screen changes; until then every card falls back deterministically.
  image: t.image ?? `/img/tea/${t.id}.jpg`,
  focal: t.focal ?? 'center',
  scrim: t.scrim ?? null,
  credit: t.credit ?? null,
  audioUrl: t.audioUrl ?? TEA_AUDIO_URL,
  durationSeconds: t.durationSeconds ?? 62,
}));

export function getTea(id: string) {
  return TEAS.find((t) => t.id === id) ?? null;
}

/**
 * Stable per calendar day, with no repeat inside a 30-day cycle. Uses whole days
 * since the epoch, so every client that agrees on the date agrees on the tea.
 */
export function teaOfDay(d: Date = new Date()): Tea {
  const day = Math.floor(d.getTime() / 86_400_000);
  const ordered = [...TEAS].sort((a, b) => a.order - b.order);
  return ordered[((day % ordered.length) + ordered.length) % ordered.length];
}

export function resolveTeaAudioUrl(tea: Tea): string | null {
  const url = tea.audioUrl ?? TEA_AUDIO_URL;
  return url.replace('{teaId}', tea.id);
}

export function teaForClient(tea: Tea) {
  const audioUrl = resolveTeaAudioUrl(tea);
  return { ...tea, hasAudio: Boolean(audioUrl), audioUrl };
}
